// Code generated by ent, DO NOT EDIT.

package secret

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the secret type in the database.
	Label = "secret"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldEncryptedValue holds the string denoting the encrypted_value field in the database.
	FieldEncryptedValue = "encrypted_value"
	// FieldSecretRef holds the string denoting the secret_ref field in the database.
	FieldSecretRef = "secret_ref"
	// FieldSecretType holds the string denoting the secret_type field in the database.
	FieldSecretType = "secret_type"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldScopeID holds the string denoting the scope_id field in the database.
	FieldScopeID = "scope_id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldInjectionMode holds the string denoting the injection_mode field in the database.
	FieldInjectionMode = "injection_mode"
	// FieldAllowProgeny holds the string denoting the allow_progeny field in the database.
	FieldAllowProgeny = "allow_progeny"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// FieldUpdated holds the string denoting the updated field in the database.
	FieldUpdated = "updated"
	// Table holds the table name of the secret in the database.
	Table = "secrets"
)

// Columns holds all SQL columns for secret fields.
var Columns = []string{
	FieldID,
	FieldKey,
	FieldEncryptedValue,
	FieldSecretRef,
	FieldSecretType,
	FieldTarget,
	FieldScope,
	FieldScopeID,
	FieldDescription,
	FieldInjectionMode,
	FieldAllowProgeny,
	FieldVersion,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldCreated,
	FieldUpdated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	ScopeValidator func(string) error
	// DefaultAllowProgeny holds the default value on creation for the "allow_progeny" field.
	DefaultAllowProgeny bool
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int
	// DefaultCreated holds the default value on creation for the "created" field.
	DefaultCreated func() time.Time
	// DefaultUpdated holds the default value on creation for the "updated" field.
	DefaultUpdated func() time.Time
	// UpdateDefaultUpdated holds the default value on update for the "updated" field.
	UpdateDefaultUpdated func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// SecretType defines the type for the "secret_type" enum field.
type SecretType string

// SecretTypeEnvironment is the default value of the SecretType enum.
const DefaultSecretType = SecretTypeEnvironment

// SecretType values.
const (
	SecretTypeEnvironment SecretType = "environment"
	SecretTypeVariable    SecretType = "variable"
	SecretTypeFile        SecretType = "file"
	SecretTypeInternal    SecretType = "internal"
)

func (st SecretType) String() string {
	return string(st)
}

// SecretTypeValidator is a validator for the "secret_type" field enum values. It is called by the builders before save.
func SecretTypeValidator(st SecretType) error {
	switch st {
	case SecretTypeEnvironment, SecretTypeVariable, SecretTypeFile, SecretTypeInternal:
		return nil
	default:
		return fmt.Errorf("secret: invalid enum value for secret_type field: %q", st)
	}
}

// InjectionMode defines the type for the "injection_mode" enum field.
type InjectionMode string

// InjectionModeAsNeeded is the default value of the InjectionMode enum.
const DefaultInjectionMode = InjectionModeAsNeeded

// InjectionMode values.
const (
	InjectionModeAlways   InjectionMode = "always"
	InjectionModeAsNeeded InjectionMode = "as_needed"
)

func (im InjectionMode) String() string {
	return string(im)
}

// InjectionModeValidator is a validator for the "injection_mode" field enum values. It is called by the builders before save.
func InjectionModeValidator(im InjectionMode) error {
	switch im {
	case InjectionModeAlways, InjectionModeAsNeeded:
		return nil
	default:
		return fmt.Errorf("secret: invalid enum value for injection_mode field: %q", im)
	}
}

// OrderOption defines the ordering options for the Secret queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByEncryptedValue orders the results by the encrypted_value field.
func ByEncryptedValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptedValue, opts...).ToFunc()
}

// BySecretRef orders the results by the secret_ref field.
func BySecretRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretRef, opts...).ToFunc()
}

// BySecretType orders the results by the secret_type field.
func BySecretType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretType, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByScopeID orders the results by the scope_id field.
func ByScopeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeID, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByInjectionMode orders the results by the injection_mode field.
func ByInjectionMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInjectionMode, opts...).ToFunc()
}

// ByAllowProgeny orders the results by the allow_progeny field.
func ByAllowProgeny(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowProgeny, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByCreated orders the results by the created field.
func ByCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreated, opts...).ToFunc()
}

// ByUpdated orders the results by the updated field.
func ByUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdated, opts...).ToFunc()
}
