// Code generated by ent, DO NOT EDIT.

package secret

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldKey, v))
}

// EncryptedValue applies equality check predicate on the "encrypted_value" field. It's identical to EncryptedValueEQ.
func EncryptedValue(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldEncryptedValue, v))
}

// SecretRef applies equality check predicate on the "secret_ref" field. It's identical to SecretRefEQ.
func SecretRef(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldSecretRef, v))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldTarget, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldScope, v))
}

// ScopeID applies equality check predicate on the "scope_id" field. It's identical to ScopeIDEQ.
func ScopeID(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldScopeID, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldDescription, v))
}

// AllowProgeny applies equality check predicate on the "allow_progeny" field. It's identical to AllowProgenyEQ.
func AllowProgeny(v bool) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldAllowProgeny, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldVersion, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldUpdatedBy, v))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldCreated, v))
}

// Updated applies equality check predicate on the "updated" field. It's identical to UpdatedEQ.
func Updated(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldUpdated, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldKey, v))
}

// EncryptedValueEQ applies the EQ predicate on the "encrypted_value" field.
func EncryptedValueEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldEncryptedValue, v))
}

// EncryptedValueNEQ applies the NEQ predicate on the "encrypted_value" field.
func EncryptedValueNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldEncryptedValue, v))
}

// EncryptedValueIn applies the In predicate on the "encrypted_value" field.
func EncryptedValueIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldEncryptedValue, vs...))
}

// EncryptedValueNotIn applies the NotIn predicate on the "encrypted_value" field.
func EncryptedValueNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldEncryptedValue, vs...))
}

// EncryptedValueGT applies the GT predicate on the "encrypted_value" field.
func EncryptedValueGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldEncryptedValue, v))
}

// EncryptedValueGTE applies the GTE predicate on the "encrypted_value" field.
func EncryptedValueGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldEncryptedValue, v))
}

// EncryptedValueLT applies the LT predicate on the "encrypted_value" field.
func EncryptedValueLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldEncryptedValue, v))
}

// EncryptedValueLTE applies the LTE predicate on the "encrypted_value" field.
func EncryptedValueLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldEncryptedValue, v))
}

// EncryptedValueContains applies the Contains predicate on the "encrypted_value" field.
func EncryptedValueContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldEncryptedValue, v))
}

// EncryptedValueHasPrefix applies the HasPrefix predicate on the "encrypted_value" field.
func EncryptedValueHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldEncryptedValue, v))
}

// EncryptedValueHasSuffix applies the HasSuffix predicate on the "encrypted_value" field.
func EncryptedValueHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldEncryptedValue, v))
}

// EncryptedValueEqualFold applies the EqualFold predicate on the "encrypted_value" field.
func EncryptedValueEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldEncryptedValue, v))
}

// EncryptedValueContainsFold applies the ContainsFold predicate on the "encrypted_value" field.
func EncryptedValueContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldEncryptedValue, v))
}

// SecretRefEQ applies the EQ predicate on the "secret_ref" field.
func SecretRefEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldSecretRef, v))
}

// SecretRefNEQ applies the NEQ predicate on the "secret_ref" field.
func SecretRefNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldSecretRef, v))
}

// SecretRefIn applies the In predicate on the "secret_ref" field.
func SecretRefIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldSecretRef, vs...))
}

// SecretRefNotIn applies the NotIn predicate on the "secret_ref" field.
func SecretRefNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldSecretRef, vs...))
}

// SecretRefGT applies the GT predicate on the "secret_ref" field.
func SecretRefGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldSecretRef, v))
}

// SecretRefGTE applies the GTE predicate on the "secret_ref" field.
func SecretRefGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldSecretRef, v))
}

// SecretRefLT applies the LT predicate on the "secret_ref" field.
func SecretRefLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldSecretRef, v))
}

// SecretRefLTE applies the LTE predicate on the "secret_ref" field.
func SecretRefLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldSecretRef, v))
}

// SecretRefContains applies the Contains predicate on the "secret_ref" field.
func SecretRefContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldSecretRef, v))
}

// SecretRefHasPrefix applies the HasPrefix predicate on the "secret_ref" field.
func SecretRefHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldSecretRef, v))
}

// SecretRefHasSuffix applies the HasSuffix predicate on the "secret_ref" field.
func SecretRefHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldSecretRef, v))
}

// SecretRefIsNil applies the IsNil predicate on the "secret_ref" field.
func SecretRefIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldSecretRef))
}

// SecretRefNotNil applies the NotNil predicate on the "secret_ref" field.
func SecretRefNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldSecretRef))
}

// SecretRefEqualFold applies the EqualFold predicate on the "secret_ref" field.
func SecretRefEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldSecretRef, v))
}

// SecretRefContainsFold applies the ContainsFold predicate on the "secret_ref" field.
func SecretRefContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldSecretRef, v))
}

// SecretTypeEQ applies the EQ predicate on the "secret_type" field.
func SecretTypeEQ(v SecretType) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldSecretType, v))
}

// SecretTypeNEQ applies the NEQ predicate on the "secret_type" field.
func SecretTypeNEQ(v SecretType) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldSecretType, v))
}

// SecretTypeIn applies the In predicate on the "secret_type" field.
func SecretTypeIn(vs ...SecretType) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldSecretType, vs...))
}

// SecretTypeNotIn applies the NotIn predicate on the "secret_type" field.
func SecretTypeNotIn(vs ...SecretType) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldSecretType, vs...))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetIsNil applies the IsNil predicate on the "target" field.
func TargetIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldTarget))
}

// TargetNotNil applies the NotNil predicate on the "target" field.
func TargetNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldTarget))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldTarget, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldScope, v))
}

// ScopeIDEQ applies the EQ predicate on the "scope_id" field.
func ScopeIDEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldScopeID, v))
}

// ScopeIDNEQ applies the NEQ predicate on the "scope_id" field.
func ScopeIDNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldScopeID, v))
}

// ScopeIDIn applies the In predicate on the "scope_id" field.
func ScopeIDIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldScopeID, vs...))
}

// ScopeIDNotIn applies the NotIn predicate on the "scope_id" field.
func ScopeIDNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldScopeID, vs...))
}

// ScopeIDGT applies the GT predicate on the "scope_id" field.
func ScopeIDGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldScopeID, v))
}

// ScopeIDGTE applies the GTE predicate on the "scope_id" field.
func ScopeIDGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldScopeID, v))
}

// ScopeIDLT applies the LT predicate on the "scope_id" field.
func ScopeIDLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldScopeID, v))
}

// ScopeIDLTE applies the LTE predicate on the "scope_id" field.
func ScopeIDLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldScopeID, v))
}

// ScopeIDContains applies the Contains predicate on the "scope_id" field.
func ScopeIDContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldScopeID, v))
}

// ScopeIDHasPrefix applies the HasPrefix predicate on the "scope_id" field.
func ScopeIDHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldScopeID, v))
}

// ScopeIDHasSuffix applies the HasSuffix predicate on the "scope_id" field.
func ScopeIDHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldScopeID, v))
}

// ScopeIDEqualFold applies the EqualFold predicate on the "scope_id" field.
func ScopeIDEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldScopeID, v))
}

// ScopeIDContainsFold applies the ContainsFold predicate on the "scope_id" field.
func ScopeIDContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldScopeID, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldDescription, v))
}

// InjectionModeEQ applies the EQ predicate on the "injection_mode" field.
func InjectionModeEQ(v InjectionMode) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldInjectionMode, v))
}

// InjectionModeNEQ applies the NEQ predicate on the "injection_mode" field.
func InjectionModeNEQ(v InjectionMode) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldInjectionMode, v))
}

// InjectionModeIn applies the In predicate on the "injection_mode" field.
func InjectionModeIn(vs ...InjectionMode) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldInjectionMode, vs...))
}

// InjectionModeNotIn applies the NotIn predicate on the "injection_mode" field.
func InjectionModeNotIn(vs ...InjectionMode) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldInjectionMode, vs...))
}

// AllowProgenyEQ applies the EQ predicate on the "allow_progeny" field.
func AllowProgenyEQ(v bool) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldAllowProgeny, v))
}

// AllowProgenyNEQ applies the NEQ predicate on the "allow_progeny" field.
func AllowProgenyNEQ(v bool) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldAllowProgeny, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldVersion, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Secret {
	return predicate.Secret(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Secret {
	return predicate.Secret(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldCreated, v))
}

// UpdatedEQ applies the EQ predicate on the "updated" field.
func UpdatedEQ(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldUpdated, v))
}

// UpdatedNEQ applies the NEQ predicate on the "updated" field.
func UpdatedNEQ(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldUpdated, v))
}

// UpdatedIn applies the In predicate on the "updated" field.
func UpdatedIn(vs ...time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldUpdated, vs...))
}

// UpdatedNotIn applies the NotIn predicate on the "updated" field.
func UpdatedNotIn(vs ...time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldUpdated, vs...))
}

// UpdatedGT applies the GT predicate on the "updated" field.
func UpdatedGT(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldUpdated, v))
}

// UpdatedGTE applies the GTE predicate on the "updated" field.
func UpdatedGTE(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldUpdated, v))
}

// UpdatedLT applies the LT predicate on the "updated" field.
func UpdatedLT(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldUpdated, v))
}

// UpdatedLTE applies the LTE predicate on the "updated" field.
func UpdatedLTE(v time.Time) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldUpdated, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Secret) predicate.Secret {
	return predicate.Secret(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Secret) predicate.Secret {
	return predicate.Secret(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Secret) predicate.Secret {
	return predicate.Secret(sql.NotPredicates(p))
}
