// Code generated by ent, DO NOT EDIT.

package message

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the message type in the database.
	Label = "message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldSender holds the string denoting the sender field in the database.
	FieldSender = "sender"
	// FieldSenderID holds the string denoting the sender_id field in the database.
	FieldSenderID = "sender_id"
	// FieldRecipient holds the string denoting the recipient field in the database.
	FieldRecipient = "recipient"
	// FieldRecipientID holds the string denoting the recipient_id field in the database.
	FieldRecipientID = "recipient_id"
	// FieldMsg holds the string denoting the msg field in the database.
	FieldMsg = "msg"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldUrgent holds the string denoting the urgent field in the database.
	FieldUrgent = "urgent"
	// FieldBroadcasted holds the string denoting the broadcasted field in the database.
	FieldBroadcasted = "broadcasted"
	// FieldRead holds the string denoting the read field in the database.
	FieldRead = "read"
	// FieldAgentID holds the string denoting the agent_id field in the database.
	FieldAgentID = "agent_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldDispatchState holds the string denoting the dispatch_state field in the database.
	FieldDispatchState = "dispatch_state"
	// FieldDispatchFailureReason holds the string denoting the dispatch_failure_reason field in the database.
	FieldDispatchFailureReason = "dispatch_failure_reason"
	// FieldDispatchedAt holds the string denoting the dispatched_at field in the database.
	FieldDispatchedAt = "dispatched_at"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// Table holds the table name of the message in the database.
	Table = "messages"
)

// Columns holds all SQL columns for message fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldSender,
	FieldSenderID,
	FieldRecipient,
	FieldRecipientID,
	FieldMsg,
	FieldType,
	FieldUrgent,
	FieldBroadcasted,
	FieldRead,
	FieldAgentID,
	FieldGroupID,
	FieldDispatchState,
	FieldDispatchFailureReason,
	FieldDispatchedAt,
	FieldCreated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SenderValidator is a validator for the "sender" field. It is called by the builders before save.
	SenderValidator func(string) error
	// RecipientValidator is a validator for the "recipient" field. It is called by the builders before save.
	RecipientValidator func(string) error
	// MsgValidator is a validator for the "msg" field. It is called by the builders before save.
	MsgValidator func(string) error
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// DefaultUrgent holds the default value on creation for the "urgent" field.
	DefaultUrgent bool
	// DefaultBroadcasted holds the default value on creation for the "broadcasted" field.
	DefaultBroadcasted bool
	// DefaultRead holds the default value on creation for the "read" field.
	DefaultRead bool
	// DefaultDispatchState holds the default value on creation for the "dispatch_state" field.
	DefaultDispatchState string
	// DefaultCreated holds the default value on creation for the "created" field.
	DefaultCreated func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Message queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// BySender orders the results by the sender field.
func BySender(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSender, opts...).ToFunc()
}

// BySenderID orders the results by the sender_id field.
func BySenderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSenderID, opts...).ToFunc()
}

// ByRecipient orders the results by the recipient field.
func ByRecipient(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipient, opts...).ToFunc()
}

// ByRecipientID orders the results by the recipient_id field.
func ByRecipientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipientID, opts...).ToFunc()
}

// ByMsg orders the results by the msg field.
func ByMsg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMsg, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByUrgent orders the results by the urgent field.
func ByUrgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUrgent, opts...).ToFunc()
}

// ByBroadcasted orders the results by the broadcasted field.
func ByBroadcasted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBroadcasted, opts...).ToFunc()
}

// ByRead orders the results by the read field.
func ByRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRead, opts...).ToFunc()
}

// ByAgentID orders the results by the agent_id field.
func ByAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByDispatchState orders the results by the dispatch_state field.
func ByDispatchState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDispatchState, opts...).ToFunc()
}

// ByDispatchFailureReason orders the results by the dispatch_failure_reason field.
func ByDispatchFailureReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDispatchFailureReason, opts...).ToFunc()
}

// ByDispatchedAt orders the results by the dispatched_at field.
func ByDispatchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDispatchedAt, opts...).ToFunc()
}

// ByCreated orders the results by the created field.
func ByCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreated, opts...).ToFunc()
}
