#!/usr/bin/env bash
# Flags legacy grove literals outside known compatibility, test, fixture, and
# example surfaces. Keep this allowlist explicit: new files with legacy names
# should either route through pkg/projectcompat or be added here with intent.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v rg >/dev/null 2>&1; then
  echo "Warning: ripgrep (rg) not found — skipping compat-literals check" >&2
  exit 0
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

rg -n 'grove|Grove|scion\.grove|grove_id|groveId|/groves' \
  cmd pkg extras \
  --glob '*.go' \
  --glob '!pkg/ent/**' >"$tmp" || true

if [[ ! -s "$tmp" ]]; then
  exit 0
fi

allowed_paths=(
  # CLI compatibility adapters, hidden deprecated aliases, and examples.
  "^cmd/broker.go$"
  "^cmd/cli_mode.go$"
  "^cmd/config.go$"
  "^cmd/delete.go$"
  "^cmd/hub.go$"
  "^cmd/hub_env.go$"
  "^cmd/hub_secret.go$"
  "^cmd/hub_token.go$"
  "^cmd/list.go$"
  "^cmd/message.go$"
  "^cmd/notifications.go$"
  "^cmd/project.go$"
  "^cmd/root.go$"
  "^cmd/scion-broker-repl/main.go$"
  "^cmd/server_dispatcher.go$"
  "^cmd/template_import.go$"
  "^cmd/template_resolution.go$"

  # Current compatibility and migration tests/fixtures.
  "^cmd/cli_mode_test.go$"
  "^cmd/common_envgather_test.go$"
  "^cmd/delete_test.go$"
  "^cmd/harness_config_install_test.go$"
  "^cmd/hub_env_test.go$"
  "^cmd/hub_secret_test.go$"
  "^cmd/message_test.go$"
  "^cmd/notifications_test.go$"
  "^cmd/server_dispatcher_test.go$"
  "^cmd/server_test.go$"
  "^cmd/sync_test.go$"
  "^cmd/template_resolution_test.go$"
  "^cmd/templates_test.go$"
  "^extras/agent-viz/internal/logparser/parser_test.go$"
  "^extras/scion-a2a-bridge/internal/bridge/metrics_test.go$"
  "^extras/scion-a2a-bridge/internal/bridge/server_test.go$"
  "^extras/scion-a2a-bridge/internal/bridge/stream_test.go$"
  "^extras/scion-a2a-bridge/internal/state/state_test.go$"
  "^extras/scion-chat-app/internal/chatapp/commands_test.go$"
  "^extras/scion-chat-app/internal/chatapp/notifications_test.go$"
  "^extras/scion-chat-app/internal/state/state_test.go$"
  "^extras/scion-telegram/internal/telegram/broker_v2_test.go$"
  "^pkg/agent/list_test.go$"
  "^pkg/agent/provision_test.go$"
  "^pkg/agent/stop_project_containers_test.go$"
  "^pkg/api/types_test.go$"
  "^pkg/config/harness_config_test.go$"
  "^pkg/config/init_project_test.go$"
  "^pkg/config/init_test.go$"
  "^pkg/config/koanf_hubcontext_test.go$"
  "^pkg/config/koanf_test.go$"
  "^pkg/config/paths_test.go$"
  "^pkg/config/project_discovery_test.go$"
  "^pkg/config/project_marker_test.go$"
  "^pkg/config/schema_test.go$"
  "^pkg/config/settings_test.go$"
  "^pkg/config/settings_v1_test.go$"
  "^pkg/config/shared_dirs_test.go$"
  "^pkg/config/templates_test.go$"
  "^pkg/config/v7_fixes_test.go$"
  "^pkg/hub/capability_marshal_test.go$"
  "^pkg/hub/events_postgres_test.go$"
  "^pkg/hub/fs_safety_test.go$"
  "^pkg/hub/handlers_broker_inbound_test.go$"
  "^pkg/hub/handlers_project_test.go$"
  "^pkg/hub/heartbeat_legacy_test.go$"
  "^pkg/hubclient/agents_test.go$"
  "^pkg/hubclient/client_test.go$"
  "^pkg/hubclient/runtime_brokers_test.go$"
  "^pkg/hubclient/templates_test.go$"
  "^pkg/hubclient/types_test.go$"
  "^pkg/hubclient/workspace_test.go$"
  "^pkg/hubsync/resolve_test.go$"
  "^pkg/hubsync/sync_test.go$"
  "^pkg/plugin/broker_plugin_test.go$"
  "^pkg/plugin/manager_test.go$"
  "^pkg/plugin/refbroker/plugin_integration_test.go$"
  "^pkg/plugin/refbroker/refbroker_test.go$"
  "^pkg/projectcompat/config_test.go$"
  "^pkg/projectcompat/labels_test.go$"
  "^pkg/projectcompat/topics_test.go$"
  "^pkg/runtime/k8s_nfs_test.go$"
  "^pkg/runtime/k8s_secrets_test.go$"
  "^pkg/runtime/k8s_shared_dirs_test.go$"
  "^pkg/runtime/podman_test.go$"
  "^pkg/runtimebroker/handlers_envgather_test.go$"
  "^pkg/runtimebroker/handlers_exec_test.go$"
  "^pkg/runtimebroker/handlers_reset_auth_test.go$"
  "^pkg/runtimebroker/handlers_test.go$"
  "^pkg/runtimebroker/heartbeat_test.go$"
  "^pkg/runtimebroker/hub_connection_test.go$"
  "^pkg/runtimebroker/protocol_mismatch_test.go$"
  "^pkg/runtimebroker/server_lookup_test.go$"
  "^pkg/runtimebroker/start_context_test.go$"
  "^pkg/runtimebroker/types_test.go$"
  "^pkg/runtimebroker/workspace_handlers_test.go$"
  "^pkg/sciontool/hooks/handlers/status_test.go$"
  "^pkg/secret/gcpbackend_test.go$"
  "^pkg/secret/localbackend_test.go$"
  "^pkg/storage/storage_test.go$"
  "^pkg/store/models_backward_compat_test.go$"
  "^pkg/util/logging/cloud_handler_test.go$"
  "^pkg/util/logging/request_log_test.go$"
  "^pkg/wsprotocol/protocol_test.go$"

  # First-party integration compatibility boundaries.
  "^extras/agent-viz/internal/logparser/parser.go$"
  "^extras/fs-watcher-tool/main.go$"
  "^extras/fs-watcher-tool/pkg/fswatcher/project.go$"
  "^extras/scion-a2a-bridge/cmd/scion-a2a-bridge/main.go$"
  "^extras/scion-a2a-bridge/internal/bridge/bridge.go$"
  "^extras/scion-a2a-bridge/internal/bridge/config.go$"
  "^extras/scion-a2a-bridge/internal/bridge/server.go$"
  "^extras/scion-chat-app/cmd/scion-chat-app/main.go$"
  "^extras/scion-chat-app/internal/chatapp/commands.go$"
  "^extras/scion-chat-app/internal/chatapp/messenger.go$"
  "^extras/scion-chat-app/internal/chatapp/notifications.go$"
  "^extras/scion-chat-app/internal/state/state.go$"
  "^extras/scion-discord/internal/discord/broker.go$"
  "^extras/scion-telegram/internal/telegram/broker_v2.go$"

  # Core compatibility adapters and bounded legacy protocol/storage surfaces.
  "^pkg/agent/list.go$"
  "^pkg/agent/msgbuffer.go$"
  "^pkg/api/types.go$"
  "^pkg/brokerclient/agents.go$"
  "^pkg/config/init.go$"
  "^pkg/config/koanf.go$"
  "^pkg/config/paths.go$"
  "^pkg/config/project_discovery.go$"
  "^pkg/config/project_marker.go$"
  "^pkg/config/settings.go$"
  "^pkg/config/settings_v1.go$"
  "^pkg/config/shared_dirs.go$"
  "^pkg/config/templates.go$"
  "^pkg/hub/events.go$"
  "^pkg/hub/events_postgres.go$"
  "^pkg/hub/fs_safety.go$"
  "^pkg/hub/handlers.go$"
  "^pkg/hub/handlers_auth.go$"
  "^pkg/hub/handlers_broker_inbound.go$"
  "^pkg/hub/handlers_notifications.go$"
  "^pkg/hub/project_cache.go$"
  "^pkg/hub/project_compat.go$"
  "^pkg/hub/project_webdav.go$"
  "^pkg/hub/response_types.go$"
  "^pkg/hub/server.go$"
  "^pkg/hub/system_handlers.go$"
  "^pkg/hub/template_handlers.go$"
  "^pkg/hub/web.go$"
  "^pkg/hubclient/agents.go$"
  "^pkg/hubclient/client.go$"
  "^pkg/hubclient/messages.go$"
  "^pkg/hubclient/notifications.go$"
  "^pkg/hubclient/projects.go$"
  "^pkg/hubclient/runtime_brokers.go$"
  "^pkg/hubclient/scheduled_events.go$"
  "^pkg/hubclient/schedules.go$"
  "^pkg/hubclient/templates.go$"
  "^pkg/hubclient/tokens.go$"
  "^pkg/hubclient/types.go$"
  "^pkg/hubsync/sync.go$"
  "^pkg/projectcompat/.*\\.go$"
  "^pkg/runtime/common.go$"
  "^pkg/runtime/k8s_runtime.go$"
  "^pkg/runtimebroker/handlers.go$"
  "^pkg/runtimebroker/pty_handlers.go$"
  "^pkg/runtimebroker/server.go$"
  "^pkg/runtimebroker/start_context.go$"
  "^pkg/runtimebroker/types.go$"
  "^pkg/runtimebroker/workspace_handlers.go$"
  "^pkg/sciontool/hooks/handlers/telemetry.go$"
  "^pkg/sciontool/telemetry/gcp_exporter.go$"
  "^pkg/sciontool/telemetry/providers.go$"
  "^pkg/storage/storage.go$"
  "^pkg/store/entadapter/composite.go$"
  "^pkg/store/models.go$"
  "^pkg/store/storetest/domains_project_broker.go$"
  "^pkg/util/logging/request_log.go$"
  "^pkg/wsprotocol/protocol.go$"
)

allowlist="$(printf '%s\n' "${allowed_paths[@]}" | sed 's/\$$/:/' | paste -sd '|' -)"

violations="$(grep -Ev "$allowlist" "$tmp" || true)"
if [[ -n "$violations" ]]; then
  echo "Legacy grove literals found outside the project compatibility allowlist:" >&2
  echo "$violations" >&2
  echo >&2
  echo "Use project vocabulary for new code, or route legacy handling through pkg/projectcompat." >&2
  exit 1
fi
