// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package entadapter

import (
	"context"
	"time"

	entsql "entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/maintenanceoperation"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/maintenanceoperationrun"
	"github.com/GoogleCloudPlatform/scion/pkg/store"
)

// MaintenanceStore implements store.MaintenanceStore using the Ent ORM.
type MaintenanceStore struct {
	client *ent.Client
}

// NewMaintenanceStore creates a new Ent-backed MaintenanceStore.
func NewMaintenanceStore(client *ent.Client) *MaintenanceStore {
	return &MaintenanceStore{client: client}
}

// abortResult is the result message stamped on operations/runs that were
// interrupted by a server restart. Kept identical to the SQLite backend.
const abortResult = `{"error":"aborted: server was restarted while operation was running"}`

// defaultSeedOperations are the built-in maintenance operations and migrations.
// In the SQLite backend these were seeded by migration SQL that minted ids via
// hex(randomblob(...)); here they are seeded in Go with ids generated by the
// Ent schema default (uuid.New) — see SeedMaintenanceOperations.
var defaultSeedOperations = []store.MaintenanceOperation{
	{
		Key:         "secret-hub-id-migration",
		Title:       "Secret Hub ID Namespace Migration",
		Description: `Migrates hub-scoped secrets from the legacy fixed "hub" scope ID to the per-instance hub ID. Required when upgrading a hub that was created before the hub ID namespacing feature. Only needed for GCP Secret Manager backend.`,
		Category:    store.MaintenanceCategoryMigration,
	},
	{
		Key:         "pull-images",
		Title:       "Pull Container Images",
		Description: "Pulls the latest container images for all configured harnesses from the image registry.",
		Category:    store.MaintenanceCategoryOperation,
	},
	{
		Key:         "rebuild-server",
		Title:       "Rebuild Server from Git",
		Description: "Pulls latest code from the repository, rebuilds the server binary and web assets, then restarts the hub service. Equivalent to the fast-deploy mode of gce-start-hub.sh.",
		Category:    store.MaintenanceCategoryOperation,
	},
	{
		Key:         "rebuild-web",
		Title:       "Rebuild Web Frontend",
		Description: "Rebuilds only the web frontend assets from source without restarting the server binary. Changes take effect on the next page load.",
		Category:    store.MaintenanceCategoryOperation,
	},
	{
		Key:         "rebuild-container-binaries",
		Title:       "Rebuild Container Binaries",
		Description: "Rebuilds scion and sciontool binaries for Linux containers (make container-binaries). Only available when SCION_DEV_BINARIES is set. Binaries are written to .build/container/ in the source checkout.",
		Category:    store.MaintenanceCategoryOperation,
	},
	{
		Key:         "build-harness-config-image",
		Title:       "Build Harness Config Image",
		Description: "Builds a container image from a harness-config's bundled Dockerfile. The base image is resolved from the configured image registry.",
		Category:    store.MaintenanceCategoryOperation,
	},
}

// ============================================================================
// Conversions
// ============================================================================

func entMaintenanceOpToStore(e *ent.MaintenanceOperation) *store.MaintenanceOperation {
	return &store.MaintenanceOperation{
		ID:          e.ID.String(),
		Key:         e.Key,
		Title:       e.Title,
		Description: e.Description,
		Category:    e.Category,
		Status:      e.Status,
		CreatedAt:   e.Created,
		StartedAt:   e.StartedAt,
		CompletedAt: e.CompletedAt,
		StartedBy:   e.StartedBy,
		Result:      e.Result,
		Metadata:    e.Metadata,
	}
}

func entMaintenanceRunToStore(e *ent.MaintenanceOperationRun) *store.MaintenanceOperationRun {
	return &store.MaintenanceOperationRun{
		ID:           e.ID.String(),
		OperationKey: e.OperationKey,
		Status:       e.Status,
		StartedAt:    e.StartedAt,
		CompletedAt:  e.CompletedAt,
		StartedBy:    e.StartedBy,
		Result:       e.Result,
		Log:          e.Log,
	}
}

// ============================================================================
// Seed
// ============================================================================

// SeedMaintenanceOperations inserts the built-in operations and migrations that
// are missing from the store. It is idempotent and replaces the SQLite
// randomblob() UUID seeds with Go-side ids generated by the Ent default.
func (s *MaintenanceStore) SeedMaintenanceOperations(ctx context.Context) error {
	for _, op := range defaultSeedOperations {
		exists, err := s.client.MaintenanceOperation.Query().
			Where(maintenanceoperation.KeyEQ(op.Key)).
			Exist(ctx)
		if err != nil {
			return err
		}
		if exists {
			continue
		}
		// ID is intentionally left unset so the Ent schema default (uuid.New)
		// mints it — the Go replacement for the SQLite randomblob() seed.
		err = s.client.MaintenanceOperation.Create().
			SetKey(op.Key).
			SetTitle(op.Title).
			SetDescription(op.Description).
			SetCategory(op.Category).
			SetStatus(store.MaintenanceStatusPending).
			Exec(ctx)
		if err != nil && !ent.IsConstraintError(err) {
			return err
		}
	}
	return nil
}

// ============================================================================
// Maintenance Operation Operations
// ============================================================================

// ListMaintenanceOperations returns all registered operations and migrations.
func (s *MaintenanceStore) ListMaintenanceOperations(ctx context.Context) ([]store.MaintenanceOperation, error) {
	entities, err := s.client.MaintenanceOperation.Query().
		Order(
			maintenanceoperation.ByCategory(),
			maintenanceoperation.ByCreated(),
		).
		All(ctx)
	if err != nil {
		return nil, err
	}
	ops := make([]store.MaintenanceOperation, 0, len(entities))
	for _, e := range entities {
		ops = append(ops, *entMaintenanceOpToStore(e))
	}
	return ops, nil
}

// GetMaintenanceOperation returns a single operation by key.
func (s *MaintenanceStore) GetMaintenanceOperation(ctx context.Context, key string) (*store.MaintenanceOperation, error) {
	e, err := s.client.MaintenanceOperation.Query().
		Where(maintenanceoperation.KeyEQ(key)).
		Only(ctx)
	if err != nil {
		return nil, mapError(err)
	}
	return entMaintenanceOpToStore(e), nil
}

// UpdateMaintenanceOperation updates an operation's status and result fields.
func (s *MaintenanceStore) UpdateMaintenanceOperation(ctx context.Context, op *store.MaintenanceOperation) error {
	update := s.client.MaintenanceOperation.Update().
		Where(maintenanceoperation.KeyEQ(op.Key)).
		SetStatus(op.Status).
		SetStartedBy(op.StartedBy).
		SetResult(op.Result).
		SetMetadata(op.Metadata)

	if op.StartedAt != nil {
		update.SetStartedAt(*op.StartedAt)
	} else {
		update.ClearStartedAt()
	}
	if op.CompletedAt != nil {
		update.SetCompletedAt(*op.CompletedAt)
	} else {
		update.ClearCompletedAt()
	}

	n, err := update.Save(ctx)
	if err != nil {
		return mapError(err)
	}
	if n == 0 {
		return store.ErrNotFound
	}
	return nil
}

// ============================================================================
// Maintenance Operation Run Operations
// ============================================================================

// CreateMaintenanceRun inserts a new run record.
func (s *MaintenanceStore) CreateMaintenanceRun(ctx context.Context, run *store.MaintenanceOperationRun) error {
	create := s.client.MaintenanceOperationRun.Create().
		SetOperationKey(run.OperationKey).
		SetStatus(run.Status).
		SetLog(run.Log)

	if run.ID != "" {
		uid, err := parseUUID(run.ID)
		if err != nil {
			return err
		}
		create.SetID(uid)
	}
	if !run.StartedAt.IsZero() {
		create.SetStartedAt(run.StartedAt)
	}
	if run.CompletedAt != nil {
		create.SetCompletedAt(*run.CompletedAt)
	}
	if run.StartedBy != "" {
		create.SetStartedBy(run.StartedBy)
	}
	if run.Result != "" {
		create.SetResult(run.Result)
	}

	created, err := create.Save(ctx)
	if err != nil {
		return mapError(err)
	}
	run.ID = created.ID.String()
	run.StartedAt = created.StartedAt
	if run.Status == "" {
		run.Status = created.Status
	}
	return nil
}

// UpdateMaintenanceRun updates a run's status, result, and log.
func (s *MaintenanceStore) UpdateMaintenanceRun(ctx context.Context, run *store.MaintenanceOperationRun) error {
	uid, err := parseUUID(run.ID)
	if err != nil {
		return err
	}

	update := s.client.MaintenanceOperationRun.Update().
		Where(maintenanceoperationrun.IDEQ(uid)).
		SetStatus(run.Status).
		SetResult(run.Result).
		SetLog(run.Log)

	if run.CompletedAt != nil {
		update.SetCompletedAt(*run.CompletedAt)
	} else {
		update.ClearCompletedAt()
	}

	n, err := update.Save(ctx)
	if err != nil {
		return mapError(err)
	}
	if n == 0 {
		return store.ErrNotFound
	}
	return nil
}

// GetMaintenanceRun returns a single run by ID.
func (s *MaintenanceStore) GetMaintenanceRun(ctx context.Context, id string) (*store.MaintenanceOperationRun, error) {
	uid, err := parseGetID(id)
	if err != nil {
		return nil, err
	}
	e, err := s.client.MaintenanceOperationRun.Get(ctx, uid)
	if err != nil {
		return nil, mapError(err)
	}
	return entMaintenanceRunToStore(e), nil
}

// ListMaintenanceRuns returns runs for a given operation key, ordered by
// started_at DESC.
func (s *MaintenanceStore) ListMaintenanceRuns(ctx context.Context, operationKey string, limit int) ([]store.MaintenanceOperationRun, error) {
	if limit <= 0 {
		limit = 20
	}
	entities, err := s.client.MaintenanceOperationRun.Query().
		Where(maintenanceoperationrun.OperationKeyEQ(operationKey)).
		Order(maintenanceoperationrun.ByStartedAt(entsql.OrderDesc())).
		Limit(limit).
		All(ctx)
	if err != nil {
		return nil, err
	}
	runs := make([]store.MaintenanceOperationRun, 0, len(entities))
	for _, e := range entities {
		runs = append(runs, *entMaintenanceRunToStore(e))
	}
	return runs, nil
}

// AbortRunningMaintenanceOps transitions any "running" operation runs to
// "failed" and resets stalled "running" migrations back to "pending" so they
// can be retried. Called at server startup to clean up operations interrupted
// by a restart.
func (s *MaintenanceStore) AbortRunningMaintenanceOps(ctx context.Context) (int64, int64, error) {
	now := time.Now()

	runs, err := s.client.MaintenanceOperationRun.Update().
		Where(maintenanceoperationrun.StatusEQ(store.MaintenanceStatusRunning)).
		SetStatus(store.MaintenanceStatusFailed).
		SetCompletedAt(now).
		SetResult(abortResult).
		Save(ctx)
	if err != nil {
		return 0, 0, err
	}

	migrations, err := s.client.MaintenanceOperation.Update().
		Where(
			maintenanceoperation.StatusEQ(store.MaintenanceStatusRunning),
			maintenanceoperation.CategoryEQ(store.MaintenanceCategoryMigration),
		).
		SetStatus(store.MaintenanceStatusPending).
		ClearStartedAt().
		ClearCompletedAt().
		SetResult(abortResult).
		Save(ctx)
	if err != nil {
		return int64(runs), 0, err
	}

	return int64(runs), int64(migrations), nil
}
