// Code generated by ent, DO NOT EDIT.

package githubinstallation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLTE(FieldID, id))
}

// AccountLogin applies equality check predicate on the "account_login" field. It's identical to AccountLoginEQ.
func AccountLogin(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldAccountLogin, v))
}

// AccountType applies equality check predicate on the "account_type" field. It's identical to AccountTypeEQ.
func AccountType(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldAccountType, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldAppID, v))
}

// Repositories applies equality check predicate on the "repositories" field. It's identical to RepositoriesEQ.
func Repositories(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldRepositories, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldStatus, v))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldCreated, v))
}

// Updated applies equality check predicate on the "updated" field. It's identical to UpdatedEQ.
func Updated(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldUpdated, v))
}

// AccountLoginEQ applies the EQ predicate on the "account_login" field.
func AccountLoginEQ(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldAccountLogin, v))
}

// AccountLoginNEQ applies the NEQ predicate on the "account_login" field.
func AccountLoginNEQ(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNEQ(FieldAccountLogin, v))
}

// AccountLoginIn applies the In predicate on the "account_login" field.
func AccountLoginIn(vs ...string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldIn(FieldAccountLogin, vs...))
}

// AccountLoginNotIn applies the NotIn predicate on the "account_login" field.
func AccountLoginNotIn(vs ...string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNotIn(FieldAccountLogin, vs...))
}

// AccountLoginGT applies the GT predicate on the "account_login" field.
func AccountLoginGT(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGT(FieldAccountLogin, v))
}

// AccountLoginGTE applies the GTE predicate on the "account_login" field.
func AccountLoginGTE(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGTE(FieldAccountLogin, v))
}

// AccountLoginLT applies the LT predicate on the "account_login" field.
func AccountLoginLT(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLT(FieldAccountLogin, v))
}

// AccountLoginLTE applies the LTE predicate on the "account_login" field.
func AccountLoginLTE(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLTE(FieldAccountLogin, v))
}

// AccountLoginContains applies the Contains predicate on the "account_login" field.
func AccountLoginContains(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldContains(FieldAccountLogin, v))
}

// AccountLoginHasPrefix applies the HasPrefix predicate on the "account_login" field.
func AccountLoginHasPrefix(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldHasPrefix(FieldAccountLogin, v))
}

// AccountLoginHasSuffix applies the HasSuffix predicate on the "account_login" field.
func AccountLoginHasSuffix(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldHasSuffix(FieldAccountLogin, v))
}

// AccountLoginEqualFold applies the EqualFold predicate on the "account_login" field.
func AccountLoginEqualFold(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEqualFold(FieldAccountLogin, v))
}

// AccountLoginContainsFold applies the ContainsFold predicate on the "account_login" field.
func AccountLoginContainsFold(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldContainsFold(FieldAccountLogin, v))
}

// AccountTypeEQ applies the EQ predicate on the "account_type" field.
func AccountTypeEQ(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldAccountType, v))
}

// AccountTypeNEQ applies the NEQ predicate on the "account_type" field.
func AccountTypeNEQ(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNEQ(FieldAccountType, v))
}

// AccountTypeIn applies the In predicate on the "account_type" field.
func AccountTypeIn(vs ...string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldIn(FieldAccountType, vs...))
}

// AccountTypeNotIn applies the NotIn predicate on the "account_type" field.
func AccountTypeNotIn(vs ...string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNotIn(FieldAccountType, vs...))
}

// AccountTypeGT applies the GT predicate on the "account_type" field.
func AccountTypeGT(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGT(FieldAccountType, v))
}

// AccountTypeGTE applies the GTE predicate on the "account_type" field.
func AccountTypeGTE(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGTE(FieldAccountType, v))
}

// AccountTypeLT applies the LT predicate on the "account_type" field.
func AccountTypeLT(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLT(FieldAccountType, v))
}

// AccountTypeLTE applies the LTE predicate on the "account_type" field.
func AccountTypeLTE(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLTE(FieldAccountType, v))
}

// AccountTypeContains applies the Contains predicate on the "account_type" field.
func AccountTypeContains(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldContains(FieldAccountType, v))
}

// AccountTypeHasPrefix applies the HasPrefix predicate on the "account_type" field.
func AccountTypeHasPrefix(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldHasPrefix(FieldAccountType, v))
}

// AccountTypeHasSuffix applies the HasSuffix predicate on the "account_type" field.
func AccountTypeHasSuffix(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldHasSuffix(FieldAccountType, v))
}

// AccountTypeEqualFold applies the EqualFold predicate on the "account_type" field.
func AccountTypeEqualFold(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEqualFold(FieldAccountType, v))
}

// AccountTypeContainsFold applies the ContainsFold predicate on the "account_type" field.
func AccountTypeContainsFold(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldContainsFold(FieldAccountType, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v int64) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLTE(FieldAppID, v))
}

// RepositoriesEQ applies the EQ predicate on the "repositories" field.
func RepositoriesEQ(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldRepositories, v))
}

// RepositoriesNEQ applies the NEQ predicate on the "repositories" field.
func RepositoriesNEQ(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNEQ(FieldRepositories, v))
}

// RepositoriesIn applies the In predicate on the "repositories" field.
func RepositoriesIn(vs ...string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldIn(FieldRepositories, vs...))
}

// RepositoriesNotIn applies the NotIn predicate on the "repositories" field.
func RepositoriesNotIn(vs ...string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNotIn(FieldRepositories, vs...))
}

// RepositoriesGT applies the GT predicate on the "repositories" field.
func RepositoriesGT(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGT(FieldRepositories, v))
}

// RepositoriesGTE applies the GTE predicate on the "repositories" field.
func RepositoriesGTE(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGTE(FieldRepositories, v))
}

// RepositoriesLT applies the LT predicate on the "repositories" field.
func RepositoriesLT(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLT(FieldRepositories, v))
}

// RepositoriesLTE applies the LTE predicate on the "repositories" field.
func RepositoriesLTE(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLTE(FieldRepositories, v))
}

// RepositoriesContains applies the Contains predicate on the "repositories" field.
func RepositoriesContains(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldContains(FieldRepositories, v))
}

// RepositoriesHasPrefix applies the HasPrefix predicate on the "repositories" field.
func RepositoriesHasPrefix(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldHasPrefix(FieldRepositories, v))
}

// RepositoriesHasSuffix applies the HasSuffix predicate on the "repositories" field.
func RepositoriesHasSuffix(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldHasSuffix(FieldRepositories, v))
}

// RepositoriesEqualFold applies the EqualFold predicate on the "repositories" field.
func RepositoriesEqualFold(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEqualFold(FieldRepositories, v))
}

// RepositoriesContainsFold applies the ContainsFold predicate on the "repositories" field.
func RepositoriesContainsFold(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldContainsFold(FieldRepositories, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLTE(FieldCreated, v))
}

// UpdatedEQ applies the EQ predicate on the "updated" field.
func UpdatedEQ(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldEQ(FieldUpdated, v))
}

// UpdatedNEQ applies the NEQ predicate on the "updated" field.
func UpdatedNEQ(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNEQ(FieldUpdated, v))
}

// UpdatedIn applies the In predicate on the "updated" field.
func UpdatedIn(vs ...time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldIn(FieldUpdated, vs...))
}

// UpdatedNotIn applies the NotIn predicate on the "updated" field.
func UpdatedNotIn(vs ...time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldNotIn(FieldUpdated, vs...))
}

// UpdatedGT applies the GT predicate on the "updated" field.
func UpdatedGT(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGT(FieldUpdated, v))
}

// UpdatedGTE applies the GTE predicate on the "updated" field.
func UpdatedGTE(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldGTE(FieldUpdated, v))
}

// UpdatedLT applies the LT predicate on the "updated" field.
func UpdatedLT(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLT(FieldUpdated, v))
}

// UpdatedLTE applies the LTE predicate on the "updated" field.
func UpdatedLTE(v time.Time) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.FieldLTE(FieldUpdated, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GithubInstallation) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GithubInstallation) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GithubInstallation) predicate.GithubInstallation {
	return predicate.GithubInstallation(sql.NotPredicates(p))
}
