// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/brokerjointoken"
	"github.com/google/uuid"
)

// BrokerJoinTokenCreate is the builder for creating a BrokerJoinToken entity.
type BrokerJoinTokenCreate struct {
	config
	mutation *BrokerJoinTokenMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTokenHash sets the "token_hash" field.
func (_c *BrokerJoinTokenCreate) SetTokenHash(v string) *BrokerJoinTokenCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *BrokerJoinTokenCreate) SetExpiresAt(v time.Time) *BrokerJoinTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *BrokerJoinTokenCreate) SetCreatedBy(v string) *BrokerJoinTokenCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreated sets the "created" field.
func (_c *BrokerJoinTokenCreate) SetCreated(v time.Time) *BrokerJoinTokenCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *BrokerJoinTokenCreate) SetNillableCreated(v *time.Time) *BrokerJoinTokenCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BrokerJoinTokenCreate) SetID(v uuid.UUID) *BrokerJoinTokenCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BrokerJoinTokenMutation object of the builder.
func (_c *BrokerJoinTokenCreate) Mutation() *BrokerJoinTokenMutation {
	return _c.mutation
}

// Save creates the BrokerJoinToken in the database.
func (_c *BrokerJoinTokenCreate) Save(ctx context.Context) (*BrokerJoinToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BrokerJoinTokenCreate) SaveX(ctx context.Context) *BrokerJoinToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BrokerJoinTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BrokerJoinTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BrokerJoinTokenCreate) defaults() {
	if _, ok := _c.mutation.Created(); !ok {
		v := brokerjointoken.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BrokerJoinTokenCreate) check() error {
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "BrokerJoinToken.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := brokerjointoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "BrokerJoinToken.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "BrokerJoinToken.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "BrokerJoinToken.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := brokerjointoken.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "BrokerJoinToken.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "BrokerJoinToken.created"`)}
	}
	return nil
}

func (_c *BrokerJoinTokenCreate) sqlSave(ctx context.Context) (*BrokerJoinToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BrokerJoinTokenCreate) createSpec() (*BrokerJoinToken, *sqlgraph.CreateSpec) {
	var (
		_node = &BrokerJoinToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(brokerjointoken.Table, sqlgraph.NewFieldSpec(brokerjointoken.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(brokerjointoken.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(brokerjointoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(brokerjointoken.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(brokerjointoken.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BrokerJoinToken.Create().
//		SetTokenHash(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BrokerJoinTokenUpsert) {
//			SetTokenHash(v+v).
//		}).
//		Exec(ctx)
func (_c *BrokerJoinTokenCreate) OnConflict(opts ...sql.ConflictOption) *BrokerJoinTokenUpsertOne {
	_c.conflict = opts
	return &BrokerJoinTokenUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BrokerJoinToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BrokerJoinTokenCreate) OnConflictColumns(columns ...string) *BrokerJoinTokenUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BrokerJoinTokenUpsertOne{
		create: _c,
	}
}

type (
	// BrokerJoinTokenUpsertOne is the builder for "upsert"-ing
	//  one BrokerJoinToken node.
	BrokerJoinTokenUpsertOne struct {
		create *BrokerJoinTokenCreate
	}

	// BrokerJoinTokenUpsert is the "OnConflict" setter.
	BrokerJoinTokenUpsert struct {
		*sql.UpdateSet
	}
)

// SetTokenHash sets the "token_hash" field.
func (u *BrokerJoinTokenUpsert) SetTokenHash(v string) *BrokerJoinTokenUpsert {
	u.Set(brokerjointoken.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *BrokerJoinTokenUpsert) UpdateTokenHash() *BrokerJoinTokenUpsert {
	u.SetExcluded(brokerjointoken.FieldTokenHash)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *BrokerJoinTokenUpsert) SetExpiresAt(v time.Time) *BrokerJoinTokenUpsert {
	u.Set(brokerjointoken.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *BrokerJoinTokenUpsert) UpdateExpiresAt() *BrokerJoinTokenUpsert {
	u.SetExcluded(brokerjointoken.FieldExpiresAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *BrokerJoinTokenUpsert) SetCreatedBy(v string) *BrokerJoinTokenUpsert {
	u.Set(brokerjointoken.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *BrokerJoinTokenUpsert) UpdateCreatedBy() *BrokerJoinTokenUpsert {
	u.SetExcluded(brokerjointoken.FieldCreatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.BrokerJoinToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(brokerjointoken.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BrokerJoinTokenUpsertOne) UpdateNewValues() *BrokerJoinTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(brokerjointoken.FieldID)
		}
		if _, exists := u.create.mutation.Created(); exists {
			s.SetIgnore(brokerjointoken.FieldCreated)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BrokerJoinToken.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BrokerJoinTokenUpsertOne) Ignore() *BrokerJoinTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BrokerJoinTokenUpsertOne) DoNothing() *BrokerJoinTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BrokerJoinTokenCreate.OnConflict
// documentation for more info.
func (u *BrokerJoinTokenUpsertOne) Update(set func(*BrokerJoinTokenUpsert)) *BrokerJoinTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BrokerJoinTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *BrokerJoinTokenUpsertOne) SetTokenHash(v string) *BrokerJoinTokenUpsertOne {
	return u.Update(func(s *BrokerJoinTokenUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *BrokerJoinTokenUpsertOne) UpdateTokenHash() *BrokerJoinTokenUpsertOne {
	return u.Update(func(s *BrokerJoinTokenUpsert) {
		s.UpdateTokenHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *BrokerJoinTokenUpsertOne) SetExpiresAt(v time.Time) *BrokerJoinTokenUpsertOne {
	return u.Update(func(s *BrokerJoinTokenUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *BrokerJoinTokenUpsertOne) UpdateExpiresAt() *BrokerJoinTokenUpsertOne {
	return u.Update(func(s *BrokerJoinTokenUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *BrokerJoinTokenUpsertOne) SetCreatedBy(v string) *BrokerJoinTokenUpsertOne {
	return u.Update(func(s *BrokerJoinTokenUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *BrokerJoinTokenUpsertOne) UpdateCreatedBy() *BrokerJoinTokenUpsertOne {
	return u.Update(func(s *BrokerJoinTokenUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *BrokerJoinTokenUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BrokerJoinTokenCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BrokerJoinTokenUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BrokerJoinTokenUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BrokerJoinTokenUpsertOne.ID is not supported by MySQL driver. Use BrokerJoinTokenUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BrokerJoinTokenUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BrokerJoinTokenCreateBulk is the builder for creating many BrokerJoinToken entities in bulk.
type BrokerJoinTokenCreateBulk struct {
	config
	err      error
	builders []*BrokerJoinTokenCreate
	conflict []sql.ConflictOption
}

// Save creates the BrokerJoinToken entities in the database.
func (_c *BrokerJoinTokenCreateBulk) Save(ctx context.Context) ([]*BrokerJoinToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BrokerJoinToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BrokerJoinTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BrokerJoinTokenCreateBulk) SaveX(ctx context.Context) []*BrokerJoinToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BrokerJoinTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BrokerJoinTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BrokerJoinToken.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BrokerJoinTokenUpsert) {
//			SetTokenHash(v+v).
//		}).
//		Exec(ctx)
func (_c *BrokerJoinTokenCreateBulk) OnConflict(opts ...sql.ConflictOption) *BrokerJoinTokenUpsertBulk {
	_c.conflict = opts
	return &BrokerJoinTokenUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BrokerJoinToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BrokerJoinTokenCreateBulk) OnConflictColumns(columns ...string) *BrokerJoinTokenUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BrokerJoinTokenUpsertBulk{
		create: _c,
	}
}

// BrokerJoinTokenUpsertBulk is the builder for "upsert"-ing
// a bulk of BrokerJoinToken nodes.
type BrokerJoinTokenUpsertBulk struct {
	create *BrokerJoinTokenCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BrokerJoinToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(brokerjointoken.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BrokerJoinTokenUpsertBulk) UpdateNewValues() *BrokerJoinTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(brokerjointoken.FieldID)
			}
			if _, exists := b.mutation.Created(); exists {
				s.SetIgnore(brokerjointoken.FieldCreated)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BrokerJoinToken.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BrokerJoinTokenUpsertBulk) Ignore() *BrokerJoinTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BrokerJoinTokenUpsertBulk) DoNothing() *BrokerJoinTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BrokerJoinTokenCreateBulk.OnConflict
// documentation for more info.
func (u *BrokerJoinTokenUpsertBulk) Update(set func(*BrokerJoinTokenUpsert)) *BrokerJoinTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BrokerJoinTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *BrokerJoinTokenUpsertBulk) SetTokenHash(v string) *BrokerJoinTokenUpsertBulk {
	return u.Update(func(s *BrokerJoinTokenUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *BrokerJoinTokenUpsertBulk) UpdateTokenHash() *BrokerJoinTokenUpsertBulk {
	return u.Update(func(s *BrokerJoinTokenUpsert) {
		s.UpdateTokenHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *BrokerJoinTokenUpsertBulk) SetExpiresAt(v time.Time) *BrokerJoinTokenUpsertBulk {
	return u.Update(func(s *BrokerJoinTokenUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *BrokerJoinTokenUpsertBulk) UpdateExpiresAt() *BrokerJoinTokenUpsertBulk {
	return u.Update(func(s *BrokerJoinTokenUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *BrokerJoinTokenUpsertBulk) SetCreatedBy(v string) *BrokerJoinTokenUpsertBulk {
	return u.Update(func(s *BrokerJoinTokenUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *BrokerJoinTokenUpsertBulk) UpdateCreatedBy() *BrokerJoinTokenUpsertBulk {
	return u.Update(func(s *BrokerJoinTokenUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *BrokerJoinTokenUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BrokerJoinTokenCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BrokerJoinTokenCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BrokerJoinTokenUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
