// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/envvar"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// EnvVarUpdate is the builder for updating EnvVar entities.
type EnvVarUpdate struct {
	config
	hooks    []Hook
	mutation *EnvVarMutation
}

// Where appends a list predicates to the EnvVarUpdate builder.
func (_u *EnvVarUpdate) Where(ps ...predicate.EnvVar) *EnvVarUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *EnvVarUpdate) SetKey(v string) *EnvVarUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *EnvVarUpdate) SetNillableKey(v *string) *EnvVarUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *EnvVarUpdate) SetValue(v string) *EnvVarUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *EnvVarUpdate) SetNillableValue(v *string) *EnvVarUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *EnvVarUpdate) SetScope(v string) *EnvVarUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *EnvVarUpdate) SetNillableScope(v *string) *EnvVarUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *EnvVarUpdate) SetScopeID(v string) *EnvVarUpdate {
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *EnvVarUpdate) SetNillableScopeID(v *string) *EnvVarUpdate {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *EnvVarUpdate) SetDescription(v string) *EnvVarUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EnvVarUpdate) SetNillableDescription(v *string) *EnvVarUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *EnvVarUpdate) ClearDescription() *EnvVarUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetSensitive sets the "sensitive" field.
func (_u *EnvVarUpdate) SetSensitive(v bool) *EnvVarUpdate {
	_u.mutation.SetSensitive(v)
	return _u
}

// SetNillableSensitive sets the "sensitive" field if the given value is not nil.
func (_u *EnvVarUpdate) SetNillableSensitive(v *bool) *EnvVarUpdate {
	if v != nil {
		_u.SetSensitive(*v)
	}
	return _u
}

// SetInjectionMode sets the "injection_mode" field.
func (_u *EnvVarUpdate) SetInjectionMode(v envvar.InjectionMode) *EnvVarUpdate {
	_u.mutation.SetInjectionMode(v)
	return _u
}

// SetNillableInjectionMode sets the "injection_mode" field if the given value is not nil.
func (_u *EnvVarUpdate) SetNillableInjectionMode(v *envvar.InjectionMode) *EnvVarUpdate {
	if v != nil {
		_u.SetInjectionMode(*v)
	}
	return _u
}

// SetSecret sets the "secret" field.
func (_u *EnvVarUpdate) SetSecret(v bool) *EnvVarUpdate {
	_u.mutation.SetSecret(v)
	return _u
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (_u *EnvVarUpdate) SetNillableSecret(v *bool) *EnvVarUpdate {
	if v != nil {
		_u.SetSecret(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *EnvVarUpdate) SetCreatedBy(v string) *EnvVarUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *EnvVarUpdate) SetNillableCreatedBy(v *string) *EnvVarUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *EnvVarUpdate) ClearCreatedBy() *EnvVarUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *EnvVarUpdate) SetUpdated(v time.Time) *EnvVarUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// Mutation returns the EnvVarMutation object of the builder.
func (_u *EnvVarUpdate) Mutation() *EnvVarMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnvVarUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvVarUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnvVarUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvVarUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvVarUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := envvar.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvVarUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := envvar.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "EnvVar.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := envvar.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "EnvVar.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InjectionMode(); ok {
		if err := envvar.InjectionModeValidator(v); err != nil {
			return &ValidationError{Name: "injection_mode", err: fmt.Errorf(`ent: validator failed for field "EnvVar.injection_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *EnvVarUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(envvar.Table, envvar.Columns, sqlgraph.NewFieldSpec(envvar.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(envvar.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(envvar.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(envvar.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(envvar.FieldScopeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(envvar.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(envvar.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Sensitive(); ok {
		_spec.SetField(envvar.FieldSensitive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.InjectionMode(); ok {
		_spec.SetField(envvar.FieldInjectionMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Secret(); ok {
		_spec.SetField(envvar.FieldSecret, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(envvar.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(envvar.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(envvar.FieldUpdated, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{envvar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnvVarUpdateOne is the builder for updating a single EnvVar entity.
type EnvVarUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnvVarMutation
}

// SetKey sets the "key" field.
func (_u *EnvVarUpdateOne) SetKey(v string) *EnvVarUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *EnvVarUpdateOne) SetNillableKey(v *string) *EnvVarUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *EnvVarUpdateOne) SetValue(v string) *EnvVarUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *EnvVarUpdateOne) SetNillableValue(v *string) *EnvVarUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *EnvVarUpdateOne) SetScope(v string) *EnvVarUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *EnvVarUpdateOne) SetNillableScope(v *string) *EnvVarUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *EnvVarUpdateOne) SetScopeID(v string) *EnvVarUpdateOne {
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *EnvVarUpdateOne) SetNillableScopeID(v *string) *EnvVarUpdateOne {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *EnvVarUpdateOne) SetDescription(v string) *EnvVarUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EnvVarUpdateOne) SetNillableDescription(v *string) *EnvVarUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *EnvVarUpdateOne) ClearDescription() *EnvVarUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetSensitive sets the "sensitive" field.
func (_u *EnvVarUpdateOne) SetSensitive(v bool) *EnvVarUpdateOne {
	_u.mutation.SetSensitive(v)
	return _u
}

// SetNillableSensitive sets the "sensitive" field if the given value is not nil.
func (_u *EnvVarUpdateOne) SetNillableSensitive(v *bool) *EnvVarUpdateOne {
	if v != nil {
		_u.SetSensitive(*v)
	}
	return _u
}

// SetInjectionMode sets the "injection_mode" field.
func (_u *EnvVarUpdateOne) SetInjectionMode(v envvar.InjectionMode) *EnvVarUpdateOne {
	_u.mutation.SetInjectionMode(v)
	return _u
}

// SetNillableInjectionMode sets the "injection_mode" field if the given value is not nil.
func (_u *EnvVarUpdateOne) SetNillableInjectionMode(v *envvar.InjectionMode) *EnvVarUpdateOne {
	if v != nil {
		_u.SetInjectionMode(*v)
	}
	return _u
}

// SetSecret sets the "secret" field.
func (_u *EnvVarUpdateOne) SetSecret(v bool) *EnvVarUpdateOne {
	_u.mutation.SetSecret(v)
	return _u
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (_u *EnvVarUpdateOne) SetNillableSecret(v *bool) *EnvVarUpdateOne {
	if v != nil {
		_u.SetSecret(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *EnvVarUpdateOne) SetCreatedBy(v string) *EnvVarUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *EnvVarUpdateOne) SetNillableCreatedBy(v *string) *EnvVarUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *EnvVarUpdateOne) ClearCreatedBy() *EnvVarUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *EnvVarUpdateOne) SetUpdated(v time.Time) *EnvVarUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// Mutation returns the EnvVarMutation object of the builder.
func (_u *EnvVarUpdateOne) Mutation() *EnvVarMutation {
	return _u.mutation
}

// Where appends a list predicates to the EnvVarUpdate builder.
func (_u *EnvVarUpdateOne) Where(ps ...predicate.EnvVar) *EnvVarUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnvVarUpdateOne) Select(field string, fields ...string) *EnvVarUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EnvVar entity.
func (_u *EnvVarUpdateOne) Save(ctx context.Context) (*EnvVar, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvVarUpdateOne) SaveX(ctx context.Context) *EnvVar {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnvVarUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvVarUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvVarUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := envvar.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvVarUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := envvar.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "EnvVar.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := envvar.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "EnvVar.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InjectionMode(); ok {
		if err := envvar.InjectionModeValidator(v); err != nil {
			return &ValidationError{Name: "injection_mode", err: fmt.Errorf(`ent: validator failed for field "EnvVar.injection_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *EnvVarUpdateOne) sqlSave(ctx context.Context) (_node *EnvVar, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(envvar.Table, envvar.Columns, sqlgraph.NewFieldSpec(envvar.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EnvVar.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, envvar.FieldID)
		for _, f := range fields {
			if !envvar.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != envvar.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(envvar.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(envvar.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(envvar.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(envvar.FieldScopeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(envvar.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(envvar.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Sensitive(); ok {
		_spec.SetField(envvar.FieldSensitive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.InjectionMode(); ok {
		_spec.SetField(envvar.FieldInjectionMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Secret(); ok {
		_spec.SetField(envvar.FieldSecret, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(envvar.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(envvar.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(envvar.FieldUpdated, field.TypeTime, value)
	}
	_node = &EnvVar{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{envvar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
