// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/harnessconfig"
	"github.com/google/uuid"
)

// HarnessConfigCreate is the builder for creating a HarnessConfig entity.
type HarnessConfigCreate struct {
	config
	mutation *HarnessConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *HarnessConfigCreate) SetName(v string) *HarnessConfigCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *HarnessConfigCreate) SetSlug(v string) *HarnessConfigCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *HarnessConfigCreate) SetDisplayName(v string) *HarnessConfigCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableDisplayName(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *HarnessConfigCreate) SetDescription(v string) *HarnessConfigCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableDescription(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetHarness sets the "harness" field.
func (_c *HarnessConfigCreate) SetHarness(v string) *HarnessConfigCreate {
	_c.mutation.SetHarness(v)
	return _c
}

// SetConfig sets the "config" field.
func (_c *HarnessConfigCreate) SetConfig(v string) *HarnessConfigCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableConfig(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetConfig(*v)
	}
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *HarnessConfigCreate) SetContentHash(v string) *HarnessConfigCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableContentHash(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetContentHash(*v)
	}
	return _c
}

// SetScope sets the "scope" field.
func (_c *HarnessConfigCreate) SetScope(v string) *HarnessConfigCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableScope(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetScopeID sets the "scope_id" field.
func (_c *HarnessConfigCreate) SetScopeID(v string) *HarnessConfigCreate {
	_c.mutation.SetScopeID(v)
	return _c
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableScopeID(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetScopeID(*v)
	}
	return _c
}

// SetStorageURI sets the "storage_uri" field.
func (_c *HarnessConfigCreate) SetStorageURI(v string) *HarnessConfigCreate {
	_c.mutation.SetStorageURI(v)
	return _c
}

// SetNillableStorageURI sets the "storage_uri" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableStorageURI(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetStorageURI(*v)
	}
	return _c
}

// SetStorageBucket sets the "storage_bucket" field.
func (_c *HarnessConfigCreate) SetStorageBucket(v string) *HarnessConfigCreate {
	_c.mutation.SetStorageBucket(v)
	return _c
}

// SetNillableStorageBucket sets the "storage_bucket" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableStorageBucket(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetStorageBucket(*v)
	}
	return _c
}

// SetStoragePath sets the "storage_path" field.
func (_c *HarnessConfigCreate) SetStoragePath(v string) *HarnessConfigCreate {
	_c.mutation.SetStoragePath(v)
	return _c
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableStoragePath(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetStoragePath(*v)
	}
	return _c
}

// SetFiles sets the "files" field.
func (_c *HarnessConfigCreate) SetFiles(v string) *HarnessConfigCreate {
	_c.mutation.SetFiles(v)
	return _c
}

// SetNillableFiles sets the "files" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableFiles(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetFiles(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *HarnessConfigCreate) SetStatus(v harnessconfig.Status) *HarnessConfigCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableStatus(v *harnessconfig.Status) *HarnessConfigCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *HarnessConfigCreate) SetOwnerID(v string) *HarnessConfigCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableOwnerID(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetOwnerID(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *HarnessConfigCreate) SetCreatedBy(v string) *HarnessConfigCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableCreatedBy(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *HarnessConfigCreate) SetUpdatedBy(v string) *HarnessConfigCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableUpdatedBy(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetSourceURL sets the "source_url" field.
func (_c *HarnessConfigCreate) SetSourceURL(v string) *HarnessConfigCreate {
	_c.mutation.SetSourceURL(v)
	return _c
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableSourceURL(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetSourceURL(*v)
	}
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *HarnessConfigCreate) SetVisibility(v string) *HarnessConfigCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableVisibility(v *string) *HarnessConfigCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *HarnessConfigCreate) SetCreated(v time.Time) *HarnessConfigCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableCreated(v *time.Time) *HarnessConfigCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *HarnessConfigCreate) SetUpdated(v time.Time) *HarnessConfigCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableUpdated(v *time.Time) *HarnessConfigCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *HarnessConfigCreate) SetID(v uuid.UUID) *HarnessConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *HarnessConfigCreate) SetNillableID(v *uuid.UUID) *HarnessConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the HarnessConfigMutation object of the builder.
func (_c *HarnessConfigCreate) Mutation() *HarnessConfigMutation {
	return _c.mutation
}

// Save creates the HarnessConfig in the database.
func (_c *HarnessConfigCreate) Save(ctx context.Context) (*HarnessConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HarnessConfigCreate) SaveX(ctx context.Context) *HarnessConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HarnessConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HarnessConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HarnessConfigCreate) defaults() {
	if _, ok := _c.mutation.Scope(); !ok {
		v := harnessconfig.DefaultScope
		_c.mutation.SetScope(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := harnessconfig.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		v := harnessconfig.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := harnessconfig.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := harnessconfig.DefaultUpdated()
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := harnessconfig.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HarnessConfigCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "HarnessConfig.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := harnessconfig.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "HarnessConfig.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "HarnessConfig.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := harnessconfig.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "HarnessConfig.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Harness(); !ok {
		return &ValidationError{Name: "harness", err: errors.New(`ent: missing required field "HarnessConfig.harness"`)}
	}
	if v, ok := _c.mutation.Harness(); ok {
		if err := harnessconfig.HarnessValidator(v); err != nil {
			return &ValidationError{Name: "harness", err: fmt.Errorf(`ent: validator failed for field "HarnessConfig.harness": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "HarnessConfig.scope"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "HarnessConfig.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := harnessconfig.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HarnessConfig.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "HarnessConfig.visibility"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "HarnessConfig.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "HarnessConfig.updated"`)}
	}
	return nil
}

func (_c *HarnessConfigCreate) sqlSave(ctx context.Context) (*HarnessConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HarnessConfigCreate) createSpec() (*HarnessConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &HarnessConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(harnessconfig.Table, sqlgraph.NewFieldSpec(harnessconfig.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(harnessconfig.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(harnessconfig.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(harnessconfig.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(harnessconfig.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Harness(); ok {
		_spec.SetField(harnessconfig.FieldHarness, field.TypeString, value)
		_node.Harness = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(harnessconfig.FieldConfig, field.TypeString, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(harnessconfig.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(harnessconfig.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.ScopeID(); ok {
		_spec.SetField(harnessconfig.FieldScopeID, field.TypeString, value)
		_node.ScopeID = value
	}
	if value, ok := _c.mutation.StorageURI(); ok {
		_spec.SetField(harnessconfig.FieldStorageURI, field.TypeString, value)
		_node.StorageURI = value
	}
	if value, ok := _c.mutation.StorageBucket(); ok {
		_spec.SetField(harnessconfig.FieldStorageBucket, field.TypeString, value)
		_node.StorageBucket = value
	}
	if value, ok := _c.mutation.StoragePath(); ok {
		_spec.SetField(harnessconfig.FieldStoragePath, field.TypeString, value)
		_node.StoragePath = value
	}
	if value, ok := _c.mutation.Files(); ok {
		_spec.SetField(harnessconfig.FieldFiles, field.TypeString, value)
		_node.Files = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(harnessconfig.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(harnessconfig.FieldOwnerID, field.TypeString, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(harnessconfig.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(harnessconfig.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.SourceURL(); ok {
		_spec.SetField(harnessconfig.FieldSourceURL, field.TypeString, value)
		_node.SourceURL = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(harnessconfig.FieldVisibility, field.TypeString, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(harnessconfig.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(harnessconfig.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HarnessConfig.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HarnessConfigUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *HarnessConfigCreate) OnConflict(opts ...sql.ConflictOption) *HarnessConfigUpsertOne {
	_c.conflict = opts
	return &HarnessConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HarnessConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HarnessConfigCreate) OnConflictColumns(columns ...string) *HarnessConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HarnessConfigUpsertOne{
		create: _c,
	}
}

type (
	// HarnessConfigUpsertOne is the builder for "upsert"-ing
	//  one HarnessConfig node.
	HarnessConfigUpsertOne struct {
		create *HarnessConfigCreate
	}

	// HarnessConfigUpsert is the "OnConflict" setter.
	HarnessConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *HarnessConfigUpsert) SetName(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateName() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldName)
	return u
}

// SetSlug sets the "slug" field.
func (u *HarnessConfigUpsert) SetSlug(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateSlug() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldSlug)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *HarnessConfigUpsert) SetDisplayName(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateDisplayName() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldDisplayName)
	return u
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *HarnessConfigUpsert) ClearDisplayName() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldDisplayName)
	return u
}

// SetDescription sets the "description" field.
func (u *HarnessConfigUpsert) SetDescription(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateDescription() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *HarnessConfigUpsert) ClearDescription() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldDescription)
	return u
}

// SetHarness sets the "harness" field.
func (u *HarnessConfigUpsert) SetHarness(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldHarness, v)
	return u
}

// UpdateHarness sets the "harness" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateHarness() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldHarness)
	return u
}

// SetConfig sets the "config" field.
func (u *HarnessConfigUpsert) SetConfig(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateConfig() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldConfig)
	return u
}

// ClearConfig clears the value of the "config" field.
func (u *HarnessConfigUpsert) ClearConfig() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldConfig)
	return u
}

// SetContentHash sets the "content_hash" field.
func (u *HarnessConfigUpsert) SetContentHash(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldContentHash, v)
	return u
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateContentHash() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldContentHash)
	return u
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *HarnessConfigUpsert) ClearContentHash() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldContentHash)
	return u
}

// SetScope sets the "scope" field.
func (u *HarnessConfigUpsert) SetScope(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateScope() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldScope)
	return u
}

// SetScopeID sets the "scope_id" field.
func (u *HarnessConfigUpsert) SetScopeID(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldScopeID, v)
	return u
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateScopeID() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldScopeID)
	return u
}

// ClearScopeID clears the value of the "scope_id" field.
func (u *HarnessConfigUpsert) ClearScopeID() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldScopeID)
	return u
}

// SetStorageURI sets the "storage_uri" field.
func (u *HarnessConfigUpsert) SetStorageURI(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldStorageURI, v)
	return u
}

// UpdateStorageURI sets the "storage_uri" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateStorageURI() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldStorageURI)
	return u
}

// ClearStorageURI clears the value of the "storage_uri" field.
func (u *HarnessConfigUpsert) ClearStorageURI() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldStorageURI)
	return u
}

// SetStorageBucket sets the "storage_bucket" field.
func (u *HarnessConfigUpsert) SetStorageBucket(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldStorageBucket, v)
	return u
}

// UpdateStorageBucket sets the "storage_bucket" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateStorageBucket() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldStorageBucket)
	return u
}

// ClearStorageBucket clears the value of the "storage_bucket" field.
func (u *HarnessConfigUpsert) ClearStorageBucket() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldStorageBucket)
	return u
}

// SetStoragePath sets the "storage_path" field.
func (u *HarnessConfigUpsert) SetStoragePath(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldStoragePath, v)
	return u
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateStoragePath() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldStoragePath)
	return u
}

// ClearStoragePath clears the value of the "storage_path" field.
func (u *HarnessConfigUpsert) ClearStoragePath() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldStoragePath)
	return u
}

// SetFiles sets the "files" field.
func (u *HarnessConfigUpsert) SetFiles(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldFiles, v)
	return u
}

// UpdateFiles sets the "files" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateFiles() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldFiles)
	return u
}

// ClearFiles clears the value of the "files" field.
func (u *HarnessConfigUpsert) ClearFiles() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldFiles)
	return u
}

// SetStatus sets the "status" field.
func (u *HarnessConfigUpsert) SetStatus(v harnessconfig.Status) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateStatus() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldStatus)
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *HarnessConfigUpsert) SetOwnerID(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldOwnerID, v)
	return u
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateOwnerID() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldOwnerID)
	return u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (u *HarnessConfigUpsert) ClearOwnerID() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldOwnerID)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *HarnessConfigUpsert) SetCreatedBy(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateCreatedBy() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *HarnessConfigUpsert) ClearCreatedBy() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *HarnessConfigUpsert) SetUpdatedBy(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateUpdatedBy() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldUpdatedBy)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *HarnessConfigUpsert) ClearUpdatedBy() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldUpdatedBy)
	return u
}

// SetSourceURL sets the "source_url" field.
func (u *HarnessConfigUpsert) SetSourceURL(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldSourceURL, v)
	return u
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateSourceURL() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldSourceURL)
	return u
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *HarnessConfigUpsert) ClearSourceURL() *HarnessConfigUpsert {
	u.SetNull(harnessconfig.FieldSourceURL)
	return u
}

// SetVisibility sets the "visibility" field.
func (u *HarnessConfigUpsert) SetVisibility(v string) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldVisibility, v)
	return u
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateVisibility() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldVisibility)
	return u
}

// SetUpdated sets the "updated" field.
func (u *HarnessConfigUpsert) SetUpdated(v time.Time) *HarnessConfigUpsert {
	u.Set(harnessconfig.FieldUpdated, v)
	return u
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *HarnessConfigUpsert) UpdateUpdated() *HarnessConfigUpsert {
	u.SetExcluded(harnessconfig.FieldUpdated)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.HarnessConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(harnessconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HarnessConfigUpsertOne) UpdateNewValues() *HarnessConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(harnessconfig.FieldID)
		}
		if _, exists := u.create.mutation.Created(); exists {
			s.SetIgnore(harnessconfig.FieldCreated)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HarnessConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HarnessConfigUpsertOne) Ignore() *HarnessConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HarnessConfigUpsertOne) DoNothing() *HarnessConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HarnessConfigCreate.OnConflict
// documentation for more info.
func (u *HarnessConfigUpsertOne) Update(set func(*HarnessConfigUpsert)) *HarnessConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HarnessConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *HarnessConfigUpsertOne) SetName(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateName() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateName()
	})
}

// SetSlug sets the "slug" field.
func (u *HarnessConfigUpsertOne) SetSlug(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateSlug() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateSlug()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *HarnessConfigUpsertOne) SetDisplayName(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateDisplayName() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateDisplayName()
	})
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *HarnessConfigUpsertOne) ClearDisplayName() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearDisplayName()
	})
}

// SetDescription sets the "description" field.
func (u *HarnessConfigUpsertOne) SetDescription(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateDescription() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *HarnessConfigUpsertOne) ClearDescription() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearDescription()
	})
}

// SetHarness sets the "harness" field.
func (u *HarnessConfigUpsertOne) SetHarness(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetHarness(v)
	})
}

// UpdateHarness sets the "harness" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateHarness() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateHarness()
	})
}

// SetConfig sets the "config" field.
func (u *HarnessConfigUpsertOne) SetConfig(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateConfig() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateConfig()
	})
}

// ClearConfig clears the value of the "config" field.
func (u *HarnessConfigUpsertOne) ClearConfig() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearConfig()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *HarnessConfigUpsertOne) SetContentHash(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateContentHash() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateContentHash()
	})
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *HarnessConfigUpsertOne) ClearContentHash() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearContentHash()
	})
}

// SetScope sets the "scope" field.
func (u *HarnessConfigUpsertOne) SetScope(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateScope() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateScope()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *HarnessConfigUpsertOne) SetScopeID(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateScopeID() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateScopeID()
	})
}

// ClearScopeID clears the value of the "scope_id" field.
func (u *HarnessConfigUpsertOne) ClearScopeID() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearScopeID()
	})
}

// SetStorageURI sets the "storage_uri" field.
func (u *HarnessConfigUpsertOne) SetStorageURI(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetStorageURI(v)
	})
}

// UpdateStorageURI sets the "storage_uri" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateStorageURI() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateStorageURI()
	})
}

// ClearStorageURI clears the value of the "storage_uri" field.
func (u *HarnessConfigUpsertOne) ClearStorageURI() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearStorageURI()
	})
}

// SetStorageBucket sets the "storage_bucket" field.
func (u *HarnessConfigUpsertOne) SetStorageBucket(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetStorageBucket(v)
	})
}

// UpdateStorageBucket sets the "storage_bucket" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateStorageBucket() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateStorageBucket()
	})
}

// ClearStorageBucket clears the value of the "storage_bucket" field.
func (u *HarnessConfigUpsertOne) ClearStorageBucket() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearStorageBucket()
	})
}

// SetStoragePath sets the "storage_path" field.
func (u *HarnessConfigUpsertOne) SetStoragePath(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetStoragePath(v)
	})
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateStoragePath() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateStoragePath()
	})
}

// ClearStoragePath clears the value of the "storage_path" field.
func (u *HarnessConfigUpsertOne) ClearStoragePath() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearStoragePath()
	})
}

// SetFiles sets the "files" field.
func (u *HarnessConfigUpsertOne) SetFiles(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetFiles(v)
	})
}

// UpdateFiles sets the "files" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateFiles() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateFiles()
	})
}

// ClearFiles clears the value of the "files" field.
func (u *HarnessConfigUpsertOne) ClearFiles() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearFiles()
	})
}

// SetStatus sets the "status" field.
func (u *HarnessConfigUpsertOne) SetStatus(v harnessconfig.Status) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateStatus() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateStatus()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *HarnessConfigUpsertOne) SetOwnerID(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateOwnerID() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateOwnerID()
	})
}

// ClearOwnerID clears the value of the "owner_id" field.
func (u *HarnessConfigUpsertOne) ClearOwnerID() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearOwnerID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *HarnessConfigUpsertOne) SetCreatedBy(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateCreatedBy() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *HarnessConfigUpsertOne) ClearCreatedBy() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *HarnessConfigUpsertOne) SetUpdatedBy(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateUpdatedBy() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *HarnessConfigUpsertOne) ClearUpdatedBy() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *HarnessConfigUpsertOne) SetSourceURL(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateSourceURL() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateSourceURL()
	})
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *HarnessConfigUpsertOne) ClearSourceURL() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearSourceURL()
	})
}

// SetVisibility sets the "visibility" field.
func (u *HarnessConfigUpsertOne) SetVisibility(v string) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateVisibility() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateVisibility()
	})
}

// SetUpdated sets the "updated" field.
func (u *HarnessConfigUpsertOne) SetUpdated(v time.Time) *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *HarnessConfigUpsertOne) UpdateUpdated() *HarnessConfigUpsertOne {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateUpdated()
	})
}

// Exec executes the query.
func (u *HarnessConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HarnessConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HarnessConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HarnessConfigUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: HarnessConfigUpsertOne.ID is not supported by MySQL driver. Use HarnessConfigUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HarnessConfigUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HarnessConfigCreateBulk is the builder for creating many HarnessConfig entities in bulk.
type HarnessConfigCreateBulk struct {
	config
	err      error
	builders []*HarnessConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the HarnessConfig entities in the database.
func (_c *HarnessConfigCreateBulk) Save(ctx context.Context) ([]*HarnessConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HarnessConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HarnessConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HarnessConfigCreateBulk) SaveX(ctx context.Context) []*HarnessConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HarnessConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HarnessConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HarnessConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HarnessConfigUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *HarnessConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *HarnessConfigUpsertBulk {
	_c.conflict = opts
	return &HarnessConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HarnessConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HarnessConfigCreateBulk) OnConflictColumns(columns ...string) *HarnessConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HarnessConfigUpsertBulk{
		create: _c,
	}
}

// HarnessConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of HarnessConfig nodes.
type HarnessConfigUpsertBulk struct {
	create *HarnessConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.HarnessConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(harnessconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HarnessConfigUpsertBulk) UpdateNewValues() *HarnessConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(harnessconfig.FieldID)
			}
			if _, exists := b.mutation.Created(); exists {
				s.SetIgnore(harnessconfig.FieldCreated)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HarnessConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HarnessConfigUpsertBulk) Ignore() *HarnessConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HarnessConfigUpsertBulk) DoNothing() *HarnessConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HarnessConfigCreateBulk.OnConflict
// documentation for more info.
func (u *HarnessConfigUpsertBulk) Update(set func(*HarnessConfigUpsert)) *HarnessConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HarnessConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *HarnessConfigUpsertBulk) SetName(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateName() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateName()
	})
}

// SetSlug sets the "slug" field.
func (u *HarnessConfigUpsertBulk) SetSlug(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateSlug() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateSlug()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *HarnessConfigUpsertBulk) SetDisplayName(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateDisplayName() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateDisplayName()
	})
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *HarnessConfigUpsertBulk) ClearDisplayName() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearDisplayName()
	})
}

// SetDescription sets the "description" field.
func (u *HarnessConfigUpsertBulk) SetDescription(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateDescription() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *HarnessConfigUpsertBulk) ClearDescription() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearDescription()
	})
}

// SetHarness sets the "harness" field.
func (u *HarnessConfigUpsertBulk) SetHarness(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetHarness(v)
	})
}

// UpdateHarness sets the "harness" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateHarness() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateHarness()
	})
}

// SetConfig sets the "config" field.
func (u *HarnessConfigUpsertBulk) SetConfig(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateConfig() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateConfig()
	})
}

// ClearConfig clears the value of the "config" field.
func (u *HarnessConfigUpsertBulk) ClearConfig() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearConfig()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *HarnessConfigUpsertBulk) SetContentHash(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateContentHash() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateContentHash()
	})
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *HarnessConfigUpsertBulk) ClearContentHash() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearContentHash()
	})
}

// SetScope sets the "scope" field.
func (u *HarnessConfigUpsertBulk) SetScope(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateScope() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateScope()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *HarnessConfigUpsertBulk) SetScopeID(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateScopeID() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateScopeID()
	})
}

// ClearScopeID clears the value of the "scope_id" field.
func (u *HarnessConfigUpsertBulk) ClearScopeID() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearScopeID()
	})
}

// SetStorageURI sets the "storage_uri" field.
func (u *HarnessConfigUpsertBulk) SetStorageURI(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetStorageURI(v)
	})
}

// UpdateStorageURI sets the "storage_uri" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateStorageURI() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateStorageURI()
	})
}

// ClearStorageURI clears the value of the "storage_uri" field.
func (u *HarnessConfigUpsertBulk) ClearStorageURI() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearStorageURI()
	})
}

// SetStorageBucket sets the "storage_bucket" field.
func (u *HarnessConfigUpsertBulk) SetStorageBucket(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetStorageBucket(v)
	})
}

// UpdateStorageBucket sets the "storage_bucket" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateStorageBucket() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateStorageBucket()
	})
}

// ClearStorageBucket clears the value of the "storage_bucket" field.
func (u *HarnessConfigUpsertBulk) ClearStorageBucket() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearStorageBucket()
	})
}

// SetStoragePath sets the "storage_path" field.
func (u *HarnessConfigUpsertBulk) SetStoragePath(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetStoragePath(v)
	})
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateStoragePath() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateStoragePath()
	})
}

// ClearStoragePath clears the value of the "storage_path" field.
func (u *HarnessConfigUpsertBulk) ClearStoragePath() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearStoragePath()
	})
}

// SetFiles sets the "files" field.
func (u *HarnessConfigUpsertBulk) SetFiles(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetFiles(v)
	})
}

// UpdateFiles sets the "files" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateFiles() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateFiles()
	})
}

// ClearFiles clears the value of the "files" field.
func (u *HarnessConfigUpsertBulk) ClearFiles() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearFiles()
	})
}

// SetStatus sets the "status" field.
func (u *HarnessConfigUpsertBulk) SetStatus(v harnessconfig.Status) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateStatus() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateStatus()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *HarnessConfigUpsertBulk) SetOwnerID(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateOwnerID() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateOwnerID()
	})
}

// ClearOwnerID clears the value of the "owner_id" field.
func (u *HarnessConfigUpsertBulk) ClearOwnerID() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearOwnerID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *HarnessConfigUpsertBulk) SetCreatedBy(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateCreatedBy() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *HarnessConfigUpsertBulk) ClearCreatedBy() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *HarnessConfigUpsertBulk) SetUpdatedBy(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateUpdatedBy() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *HarnessConfigUpsertBulk) ClearUpdatedBy() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *HarnessConfigUpsertBulk) SetSourceURL(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateSourceURL() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateSourceURL()
	})
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *HarnessConfigUpsertBulk) ClearSourceURL() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.ClearSourceURL()
	})
}

// SetVisibility sets the "visibility" field.
func (u *HarnessConfigUpsertBulk) SetVisibility(v string) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateVisibility() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateVisibility()
	})
}

// SetUpdated sets the "updated" field.
func (u *HarnessConfigUpsertBulk) SetUpdated(v time.Time) *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *HarnessConfigUpsertBulk) UpdateUpdated() *HarnessConfigUpsertBulk {
	return u.Update(func(s *HarnessConfigUpsert) {
		s.UpdateUpdated()
	})
}

// Exec executes the query.
func (u *HarnessConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HarnessConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HarnessConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HarnessConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
