// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/lifecyclehookagentphase"
)

// LifecycleHookAgentPhase is the model entity for the LifecycleHookAgentPhase schema.
type LifecycleHookAgentPhase struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AgentID holds the value of the "agent_id" field.
	AgentID string `json:"agent_id,omitempty"`
	// LastPhase holds the value of the "last_phase" field.
	LastPhase string `json:"last_phase,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LifecycleHookAgentPhase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lifecyclehookagentphase.FieldID:
			values[i] = new(sql.NullInt64)
		case lifecyclehookagentphase.FieldAgentID, lifecyclehookagentphase.FieldLastPhase:
			values[i] = new(sql.NullString)
		case lifecyclehookagentphase.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LifecycleHookAgentPhase fields.
func (_m *LifecycleHookAgentPhase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lifecyclehookagentphase.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case lifecyclehookagentphase.FieldAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value.Valid {
				_m.AgentID = value.String
			}
		case lifecyclehookagentphase.FieldLastPhase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_phase", values[i])
			} else if value.Valid {
				_m.LastPhase = value.String
			}
		case lifecyclehookagentphase.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LifecycleHookAgentPhase.
// This includes values selected through modifiers, order, etc.
func (_m *LifecycleHookAgentPhase) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LifecycleHookAgentPhase.
// Note that you need to call LifecycleHookAgentPhase.Unwrap() before calling this method if this LifecycleHookAgentPhase
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LifecycleHookAgentPhase) Update() *LifecycleHookAgentPhaseUpdateOne {
	return NewLifecycleHookAgentPhaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LifecycleHookAgentPhase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LifecycleHookAgentPhase) Unwrap() *LifecycleHookAgentPhase {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LifecycleHookAgentPhase is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LifecycleHookAgentPhase) String() string {
	var builder strings.Builder
	builder.WriteString("LifecycleHookAgentPhase(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("agent_id=")
	builder.WriteString(_m.AgentID)
	builder.WriteString(", ")
	builder.WriteString("last_phase=")
	builder.WriteString(_m.LastPhase)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LifecycleHookAgentPhases is a parsable slice of LifecycleHookAgentPhase.
type LifecycleHookAgentPhases []*LifecycleHookAgentPhase
