// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/maintenanceoperationrun"
	"github.com/google/uuid"
)

// MaintenanceOperationRunCreate is the builder for creating a MaintenanceOperationRun entity.
type MaintenanceOperationRunCreate struct {
	config
	mutation *MaintenanceOperationRunMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOperationKey sets the "operation_key" field.
func (_c *MaintenanceOperationRunCreate) SetOperationKey(v string) *MaintenanceOperationRunCreate {
	_c.mutation.SetOperationKey(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MaintenanceOperationRunCreate) SetStatus(v string) *MaintenanceOperationRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MaintenanceOperationRunCreate) SetNillableStatus(v *string) *MaintenanceOperationRunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *MaintenanceOperationRunCreate) SetStartedAt(v time.Time) *MaintenanceOperationRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *MaintenanceOperationRunCreate) SetNillableStartedAt(v *time.Time) *MaintenanceOperationRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *MaintenanceOperationRunCreate) SetCompletedAt(v time.Time) *MaintenanceOperationRunCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *MaintenanceOperationRunCreate) SetNillableCompletedAt(v *time.Time) *MaintenanceOperationRunCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetStartedBy sets the "started_by" field.
func (_c *MaintenanceOperationRunCreate) SetStartedBy(v string) *MaintenanceOperationRunCreate {
	_c.mutation.SetStartedBy(v)
	return _c
}

// SetNillableStartedBy sets the "started_by" field if the given value is not nil.
func (_c *MaintenanceOperationRunCreate) SetNillableStartedBy(v *string) *MaintenanceOperationRunCreate {
	if v != nil {
		_c.SetStartedBy(*v)
	}
	return _c
}

// SetResult sets the "result" field.
func (_c *MaintenanceOperationRunCreate) SetResult(v string) *MaintenanceOperationRunCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *MaintenanceOperationRunCreate) SetNillableResult(v *string) *MaintenanceOperationRunCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetLog sets the "log" field.
func (_c *MaintenanceOperationRunCreate) SetLog(v string) *MaintenanceOperationRunCreate {
	_c.mutation.SetLog(v)
	return _c
}

// SetNillableLog sets the "log" field if the given value is not nil.
func (_c *MaintenanceOperationRunCreate) SetNillableLog(v *string) *MaintenanceOperationRunCreate {
	if v != nil {
		_c.SetLog(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MaintenanceOperationRunCreate) SetID(v uuid.UUID) *MaintenanceOperationRunCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MaintenanceOperationRunCreate) SetNillableID(v *uuid.UUID) *MaintenanceOperationRunCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MaintenanceOperationRunMutation object of the builder.
func (_c *MaintenanceOperationRunCreate) Mutation() *MaintenanceOperationRunMutation {
	return _c.mutation
}

// Save creates the MaintenanceOperationRun in the database.
func (_c *MaintenanceOperationRunCreate) Save(ctx context.Context) (*MaintenanceOperationRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MaintenanceOperationRunCreate) SaveX(ctx context.Context) *MaintenanceOperationRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MaintenanceOperationRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MaintenanceOperationRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MaintenanceOperationRunCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := maintenanceoperationrun.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := maintenanceoperationrun.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
	if _, ok := _c.mutation.Log(); !ok {
		v := maintenanceoperationrun.DefaultLog
		_c.mutation.SetLog(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := maintenanceoperationrun.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MaintenanceOperationRunCreate) check() error {
	if _, ok := _c.mutation.OperationKey(); !ok {
		return &ValidationError{Name: "operation_key", err: errors.New(`ent: missing required field "MaintenanceOperationRun.operation_key"`)}
	}
	if v, ok := _c.mutation.OperationKey(); ok {
		if err := maintenanceoperationrun.OperationKeyValidator(v); err != nil {
			return &ValidationError{Name: "operation_key", err: fmt.Errorf(`ent: validator failed for field "MaintenanceOperationRun.operation_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MaintenanceOperationRun.status"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "MaintenanceOperationRun.started_at"`)}
	}
	if _, ok := _c.mutation.Log(); !ok {
		return &ValidationError{Name: "log", err: errors.New(`ent: missing required field "MaintenanceOperationRun.log"`)}
	}
	return nil
}

func (_c *MaintenanceOperationRunCreate) sqlSave(ctx context.Context) (*MaintenanceOperationRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MaintenanceOperationRunCreate) createSpec() (*MaintenanceOperationRun, *sqlgraph.CreateSpec) {
	var (
		_node = &MaintenanceOperationRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(maintenanceoperationrun.Table, sqlgraph.NewFieldSpec(maintenanceoperationrun.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OperationKey(); ok {
		_spec.SetField(maintenanceoperationrun.FieldOperationKey, field.TypeString, value)
		_node.OperationKey = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(maintenanceoperationrun.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(maintenanceoperationrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(maintenanceoperationrun.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.StartedBy(); ok {
		_spec.SetField(maintenanceoperationrun.FieldStartedBy, field.TypeString, value)
		_node.StartedBy = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(maintenanceoperationrun.FieldResult, field.TypeString, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.Log(); ok {
		_spec.SetField(maintenanceoperationrun.FieldLog, field.TypeString, value)
		_node.Log = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MaintenanceOperationRun.Create().
//		SetOperationKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MaintenanceOperationRunUpsert) {
//			SetOperationKey(v+v).
//		}).
//		Exec(ctx)
func (_c *MaintenanceOperationRunCreate) OnConflict(opts ...sql.ConflictOption) *MaintenanceOperationRunUpsertOne {
	_c.conflict = opts
	return &MaintenanceOperationRunUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MaintenanceOperationRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MaintenanceOperationRunCreate) OnConflictColumns(columns ...string) *MaintenanceOperationRunUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MaintenanceOperationRunUpsertOne{
		create: _c,
	}
}

type (
	// MaintenanceOperationRunUpsertOne is the builder for "upsert"-ing
	//  one MaintenanceOperationRun node.
	MaintenanceOperationRunUpsertOne struct {
		create *MaintenanceOperationRunCreate
	}

	// MaintenanceOperationRunUpsert is the "OnConflict" setter.
	MaintenanceOperationRunUpsert struct {
		*sql.UpdateSet
	}
)

// SetOperationKey sets the "operation_key" field.
func (u *MaintenanceOperationRunUpsert) SetOperationKey(v string) *MaintenanceOperationRunUpsert {
	u.Set(maintenanceoperationrun.FieldOperationKey, v)
	return u
}

// UpdateOperationKey sets the "operation_key" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsert) UpdateOperationKey() *MaintenanceOperationRunUpsert {
	u.SetExcluded(maintenanceoperationrun.FieldOperationKey)
	return u
}

// SetStatus sets the "status" field.
func (u *MaintenanceOperationRunUpsert) SetStatus(v string) *MaintenanceOperationRunUpsert {
	u.Set(maintenanceoperationrun.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsert) UpdateStatus() *MaintenanceOperationRunUpsert {
	u.SetExcluded(maintenanceoperationrun.FieldStatus)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *MaintenanceOperationRunUpsert) SetCompletedAt(v time.Time) *MaintenanceOperationRunUpsert {
	u.Set(maintenanceoperationrun.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsert) UpdateCompletedAt() *MaintenanceOperationRunUpsert {
	u.SetExcluded(maintenanceoperationrun.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *MaintenanceOperationRunUpsert) ClearCompletedAt() *MaintenanceOperationRunUpsert {
	u.SetNull(maintenanceoperationrun.FieldCompletedAt)
	return u
}

// SetStartedBy sets the "started_by" field.
func (u *MaintenanceOperationRunUpsert) SetStartedBy(v string) *MaintenanceOperationRunUpsert {
	u.Set(maintenanceoperationrun.FieldStartedBy, v)
	return u
}

// UpdateStartedBy sets the "started_by" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsert) UpdateStartedBy() *MaintenanceOperationRunUpsert {
	u.SetExcluded(maintenanceoperationrun.FieldStartedBy)
	return u
}

// ClearStartedBy clears the value of the "started_by" field.
func (u *MaintenanceOperationRunUpsert) ClearStartedBy() *MaintenanceOperationRunUpsert {
	u.SetNull(maintenanceoperationrun.FieldStartedBy)
	return u
}

// SetResult sets the "result" field.
func (u *MaintenanceOperationRunUpsert) SetResult(v string) *MaintenanceOperationRunUpsert {
	u.Set(maintenanceoperationrun.FieldResult, v)
	return u
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsert) UpdateResult() *MaintenanceOperationRunUpsert {
	u.SetExcluded(maintenanceoperationrun.FieldResult)
	return u
}

// ClearResult clears the value of the "result" field.
func (u *MaintenanceOperationRunUpsert) ClearResult() *MaintenanceOperationRunUpsert {
	u.SetNull(maintenanceoperationrun.FieldResult)
	return u
}

// SetLog sets the "log" field.
func (u *MaintenanceOperationRunUpsert) SetLog(v string) *MaintenanceOperationRunUpsert {
	u.Set(maintenanceoperationrun.FieldLog, v)
	return u
}

// UpdateLog sets the "log" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsert) UpdateLog() *MaintenanceOperationRunUpsert {
	u.SetExcluded(maintenanceoperationrun.FieldLog)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MaintenanceOperationRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(maintenanceoperationrun.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MaintenanceOperationRunUpsertOne) UpdateNewValues() *MaintenanceOperationRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(maintenanceoperationrun.FieldID)
		}
		if _, exists := u.create.mutation.StartedAt(); exists {
			s.SetIgnore(maintenanceoperationrun.FieldStartedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MaintenanceOperationRun.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MaintenanceOperationRunUpsertOne) Ignore() *MaintenanceOperationRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MaintenanceOperationRunUpsertOne) DoNothing() *MaintenanceOperationRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MaintenanceOperationRunCreate.OnConflict
// documentation for more info.
func (u *MaintenanceOperationRunUpsertOne) Update(set func(*MaintenanceOperationRunUpsert)) *MaintenanceOperationRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MaintenanceOperationRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetOperationKey sets the "operation_key" field.
func (u *MaintenanceOperationRunUpsertOne) SetOperationKey(v string) *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.SetOperationKey(v)
	})
}

// UpdateOperationKey sets the "operation_key" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsertOne) UpdateOperationKey() *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.UpdateOperationKey()
	})
}

// SetStatus sets the "status" field.
func (u *MaintenanceOperationRunUpsertOne) SetStatus(v string) *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsertOne) UpdateStatus() *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.UpdateStatus()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *MaintenanceOperationRunUpsertOne) SetCompletedAt(v time.Time) *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsertOne) UpdateCompletedAt() *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *MaintenanceOperationRunUpsertOne) ClearCompletedAt() *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.ClearCompletedAt()
	})
}

// SetStartedBy sets the "started_by" field.
func (u *MaintenanceOperationRunUpsertOne) SetStartedBy(v string) *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.SetStartedBy(v)
	})
}

// UpdateStartedBy sets the "started_by" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsertOne) UpdateStartedBy() *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.UpdateStartedBy()
	})
}

// ClearStartedBy clears the value of the "started_by" field.
func (u *MaintenanceOperationRunUpsertOne) ClearStartedBy() *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.ClearStartedBy()
	})
}

// SetResult sets the "result" field.
func (u *MaintenanceOperationRunUpsertOne) SetResult(v string) *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsertOne) UpdateResult() *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.UpdateResult()
	})
}

// ClearResult clears the value of the "result" field.
func (u *MaintenanceOperationRunUpsertOne) ClearResult() *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.ClearResult()
	})
}

// SetLog sets the "log" field.
func (u *MaintenanceOperationRunUpsertOne) SetLog(v string) *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.SetLog(v)
	})
}

// UpdateLog sets the "log" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsertOne) UpdateLog() *MaintenanceOperationRunUpsertOne {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.UpdateLog()
	})
}

// Exec executes the query.
func (u *MaintenanceOperationRunUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MaintenanceOperationRunCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MaintenanceOperationRunUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MaintenanceOperationRunUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MaintenanceOperationRunUpsertOne.ID is not supported by MySQL driver. Use MaintenanceOperationRunUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MaintenanceOperationRunUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MaintenanceOperationRunCreateBulk is the builder for creating many MaintenanceOperationRun entities in bulk.
type MaintenanceOperationRunCreateBulk struct {
	config
	err      error
	builders []*MaintenanceOperationRunCreate
	conflict []sql.ConflictOption
}

// Save creates the MaintenanceOperationRun entities in the database.
func (_c *MaintenanceOperationRunCreateBulk) Save(ctx context.Context) ([]*MaintenanceOperationRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MaintenanceOperationRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MaintenanceOperationRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MaintenanceOperationRunCreateBulk) SaveX(ctx context.Context) []*MaintenanceOperationRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MaintenanceOperationRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MaintenanceOperationRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MaintenanceOperationRun.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MaintenanceOperationRunUpsert) {
//			SetOperationKey(v+v).
//		}).
//		Exec(ctx)
func (_c *MaintenanceOperationRunCreateBulk) OnConflict(opts ...sql.ConflictOption) *MaintenanceOperationRunUpsertBulk {
	_c.conflict = opts
	return &MaintenanceOperationRunUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MaintenanceOperationRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MaintenanceOperationRunCreateBulk) OnConflictColumns(columns ...string) *MaintenanceOperationRunUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MaintenanceOperationRunUpsertBulk{
		create: _c,
	}
}

// MaintenanceOperationRunUpsertBulk is the builder for "upsert"-ing
// a bulk of MaintenanceOperationRun nodes.
type MaintenanceOperationRunUpsertBulk struct {
	create *MaintenanceOperationRunCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MaintenanceOperationRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(maintenanceoperationrun.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MaintenanceOperationRunUpsertBulk) UpdateNewValues() *MaintenanceOperationRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(maintenanceoperationrun.FieldID)
			}
			if _, exists := b.mutation.StartedAt(); exists {
				s.SetIgnore(maintenanceoperationrun.FieldStartedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MaintenanceOperationRun.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MaintenanceOperationRunUpsertBulk) Ignore() *MaintenanceOperationRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MaintenanceOperationRunUpsertBulk) DoNothing() *MaintenanceOperationRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MaintenanceOperationRunCreateBulk.OnConflict
// documentation for more info.
func (u *MaintenanceOperationRunUpsertBulk) Update(set func(*MaintenanceOperationRunUpsert)) *MaintenanceOperationRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MaintenanceOperationRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetOperationKey sets the "operation_key" field.
func (u *MaintenanceOperationRunUpsertBulk) SetOperationKey(v string) *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.SetOperationKey(v)
	})
}

// UpdateOperationKey sets the "operation_key" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsertBulk) UpdateOperationKey() *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.UpdateOperationKey()
	})
}

// SetStatus sets the "status" field.
func (u *MaintenanceOperationRunUpsertBulk) SetStatus(v string) *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsertBulk) UpdateStatus() *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.UpdateStatus()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *MaintenanceOperationRunUpsertBulk) SetCompletedAt(v time.Time) *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsertBulk) UpdateCompletedAt() *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *MaintenanceOperationRunUpsertBulk) ClearCompletedAt() *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.ClearCompletedAt()
	})
}

// SetStartedBy sets the "started_by" field.
func (u *MaintenanceOperationRunUpsertBulk) SetStartedBy(v string) *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.SetStartedBy(v)
	})
}

// UpdateStartedBy sets the "started_by" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsertBulk) UpdateStartedBy() *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.UpdateStartedBy()
	})
}

// ClearStartedBy clears the value of the "started_by" field.
func (u *MaintenanceOperationRunUpsertBulk) ClearStartedBy() *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.ClearStartedBy()
	})
}

// SetResult sets the "result" field.
func (u *MaintenanceOperationRunUpsertBulk) SetResult(v string) *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsertBulk) UpdateResult() *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.UpdateResult()
	})
}

// ClearResult clears the value of the "result" field.
func (u *MaintenanceOperationRunUpsertBulk) ClearResult() *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.ClearResult()
	})
}

// SetLog sets the "log" field.
func (u *MaintenanceOperationRunUpsertBulk) SetLog(v string) *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.SetLog(v)
	})
}

// UpdateLog sets the "log" field to the value that was provided on create.
func (u *MaintenanceOperationRunUpsertBulk) UpdateLog() *MaintenanceOperationRunUpsertBulk {
	return u.Update(func(s *MaintenanceOperationRunUpsert) {
		s.UpdateLog()
	})
}

// Exec executes the query.
func (u *MaintenanceOperationRunUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MaintenanceOperationRunCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MaintenanceOperationRunCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MaintenanceOperationRunUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
