// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/notificationsubscription"
	"github.com/google/uuid"
)

// NotificationSubscriptionCreate is the builder for creating a NotificationSubscription entity.
type NotificationSubscriptionCreate struct {
	config
	mutation *NotificationSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetScope sets the "scope" field.
func (_c *NotificationSubscriptionCreate) SetScope(v string) *NotificationSubscriptionCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *NotificationSubscriptionCreate) SetNillableScope(v *string) *NotificationSubscriptionCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *NotificationSubscriptionCreate) SetAgentID(v uuid.UUID) *NotificationSubscriptionCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_c *NotificationSubscriptionCreate) SetNillableAgentID(v *uuid.UUID) *NotificationSubscriptionCreate {
	if v != nil {
		_c.SetAgentID(*v)
	}
	return _c
}

// SetSubscriberType sets the "subscriber_type" field.
func (_c *NotificationSubscriptionCreate) SetSubscriberType(v string) *NotificationSubscriptionCreate {
	_c.mutation.SetSubscriberType(v)
	return _c
}

// SetNillableSubscriberType sets the "subscriber_type" field if the given value is not nil.
func (_c *NotificationSubscriptionCreate) SetNillableSubscriberType(v *string) *NotificationSubscriptionCreate {
	if v != nil {
		_c.SetSubscriberType(*v)
	}
	return _c
}

// SetSubscriberID sets the "subscriber_id" field.
func (_c *NotificationSubscriptionCreate) SetSubscriberID(v string) *NotificationSubscriptionCreate {
	_c.mutation.SetSubscriberID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *NotificationSubscriptionCreate) SetProjectID(v uuid.UUID) *NotificationSubscriptionCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetTriggerActivities sets the "trigger_activities" field.
func (_c *NotificationSubscriptionCreate) SetTriggerActivities(v string) *NotificationSubscriptionCreate {
	_c.mutation.SetTriggerActivities(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *NotificationSubscriptionCreate) SetCreatedBy(v string) *NotificationSubscriptionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreated sets the "created" field.
func (_c *NotificationSubscriptionCreate) SetCreated(v time.Time) *NotificationSubscriptionCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *NotificationSubscriptionCreate) SetNillableCreated(v *time.Time) *NotificationSubscriptionCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationSubscriptionCreate) SetID(v uuid.UUID) *NotificationSubscriptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NotificationSubscriptionCreate) SetNillableID(v *uuid.UUID) *NotificationSubscriptionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the NotificationSubscriptionMutation object of the builder.
func (_c *NotificationSubscriptionCreate) Mutation() *NotificationSubscriptionMutation {
	return _c.mutation
}

// Save creates the NotificationSubscription in the database.
func (_c *NotificationSubscriptionCreate) Save(ctx context.Context) (*NotificationSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationSubscriptionCreate) SaveX(ctx context.Context) *NotificationSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.Scope(); !ok {
		v := notificationsubscription.DefaultScope
		_c.mutation.SetScope(v)
	}
	if _, ok := _c.mutation.SubscriberType(); !ok {
		v := notificationsubscription.DefaultSubscriberType
		_c.mutation.SetSubscriberType(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := notificationsubscription.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := notificationsubscription.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationSubscriptionCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "NotificationSubscription.scope"`)}
	}
	if _, ok := _c.mutation.SubscriberType(); !ok {
		return &ValidationError{Name: "subscriber_type", err: errors.New(`ent: missing required field "NotificationSubscription.subscriber_type"`)}
	}
	if _, ok := _c.mutation.SubscriberID(); !ok {
		return &ValidationError{Name: "subscriber_id", err: errors.New(`ent: missing required field "NotificationSubscription.subscriber_id"`)}
	}
	if v, ok := _c.mutation.SubscriberID(); ok {
		if err := notificationsubscription.SubscriberIDValidator(v); err != nil {
			return &ValidationError{Name: "subscriber_id", err: fmt.Errorf(`ent: validator failed for field "NotificationSubscription.subscriber_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "NotificationSubscription.project_id"`)}
	}
	if _, ok := _c.mutation.TriggerActivities(); !ok {
		return &ValidationError{Name: "trigger_activities", err: errors.New(`ent: missing required field "NotificationSubscription.trigger_activities"`)}
	}
	if v, ok := _c.mutation.TriggerActivities(); ok {
		if err := notificationsubscription.TriggerActivitiesValidator(v); err != nil {
			return &ValidationError{Name: "trigger_activities", err: fmt.Errorf(`ent: validator failed for field "NotificationSubscription.trigger_activities": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "NotificationSubscription.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := notificationsubscription.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "NotificationSubscription.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "NotificationSubscription.created"`)}
	}
	return nil
}

func (_c *NotificationSubscriptionCreate) sqlSave(ctx context.Context) (*NotificationSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationSubscriptionCreate) createSpec() (*NotificationSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationsubscription.Table, sqlgraph.NewFieldSpec(notificationsubscription.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(notificationsubscription.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(notificationsubscription.FieldAgentID, field.TypeUUID, value)
		_node.AgentID = &value
	}
	if value, ok := _c.mutation.SubscriberType(); ok {
		_spec.SetField(notificationsubscription.FieldSubscriberType, field.TypeString, value)
		_node.SubscriberType = value
	}
	if value, ok := _c.mutation.SubscriberID(); ok {
		_spec.SetField(notificationsubscription.FieldSubscriberID, field.TypeString, value)
		_node.SubscriberID = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(notificationsubscription.FieldProjectID, field.TypeUUID, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.TriggerActivities(); ok {
		_spec.SetField(notificationsubscription.FieldTriggerActivities, field.TypeString, value)
		_node.TriggerActivities = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(notificationsubscription.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(notificationsubscription.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationSubscription.Create().
//		SetScope(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationSubscriptionUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *NotificationSubscriptionUpsertOne {
	_c.conflict = opts
	return &NotificationSubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationSubscriptionCreate) OnConflictColumns(columns ...string) *NotificationSubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationSubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// NotificationSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one NotificationSubscription node.
	NotificationSubscriptionUpsertOne struct {
		create *NotificationSubscriptionCreate
	}

	// NotificationSubscriptionUpsert is the "OnConflict" setter.
	NotificationSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetScope sets the "scope" field.
func (u *NotificationSubscriptionUpsert) SetScope(v string) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateScope() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldScope)
	return u
}

// SetAgentID sets the "agent_id" field.
func (u *NotificationSubscriptionUpsert) SetAgentID(v uuid.UUID) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldAgentID, v)
	return u
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateAgentID() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldAgentID)
	return u
}

// ClearAgentID clears the value of the "agent_id" field.
func (u *NotificationSubscriptionUpsert) ClearAgentID() *NotificationSubscriptionUpsert {
	u.SetNull(notificationsubscription.FieldAgentID)
	return u
}

// SetSubscriberType sets the "subscriber_type" field.
func (u *NotificationSubscriptionUpsert) SetSubscriberType(v string) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldSubscriberType, v)
	return u
}

// UpdateSubscriberType sets the "subscriber_type" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateSubscriberType() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldSubscriberType)
	return u
}

// SetSubscriberID sets the "subscriber_id" field.
func (u *NotificationSubscriptionUpsert) SetSubscriberID(v string) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldSubscriberID, v)
	return u
}

// UpdateSubscriberID sets the "subscriber_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateSubscriberID() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldSubscriberID)
	return u
}

// SetProjectID sets the "project_id" field.
func (u *NotificationSubscriptionUpsert) SetProjectID(v uuid.UUID) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateProjectID() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldProjectID)
	return u
}

// SetTriggerActivities sets the "trigger_activities" field.
func (u *NotificationSubscriptionUpsert) SetTriggerActivities(v string) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldTriggerActivities, v)
	return u
}

// UpdateTriggerActivities sets the "trigger_activities" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateTriggerActivities() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldTriggerActivities)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *NotificationSubscriptionUpsert) SetCreatedBy(v string) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateCreatedBy() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldCreatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NotificationSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationsubscription.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationSubscriptionUpsertOne) UpdateNewValues() *NotificationSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(notificationsubscription.FieldID)
		}
		if _, exists := u.create.mutation.Created(); exists {
			s.SetIgnore(notificationsubscription.FieldCreated)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotificationSubscriptionUpsertOne) Ignore() *NotificationSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationSubscriptionUpsertOne) DoNothing() *NotificationSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationSubscriptionCreate.OnConflict
// documentation for more info.
func (u *NotificationSubscriptionUpsertOne) Update(set func(*NotificationSubscriptionUpsert)) *NotificationSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *NotificationSubscriptionUpsertOne) SetScope(v string) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateScope() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateScope()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *NotificationSubscriptionUpsertOne) SetAgentID(v uuid.UUID) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateAgentID() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateAgentID()
	})
}

// ClearAgentID clears the value of the "agent_id" field.
func (u *NotificationSubscriptionUpsertOne) ClearAgentID() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.ClearAgentID()
	})
}

// SetSubscriberType sets the "subscriber_type" field.
func (u *NotificationSubscriptionUpsertOne) SetSubscriberType(v string) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetSubscriberType(v)
	})
}

// UpdateSubscriberType sets the "subscriber_type" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateSubscriberType() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateSubscriberType()
	})
}

// SetSubscriberID sets the "subscriber_id" field.
func (u *NotificationSubscriptionUpsertOne) SetSubscriberID(v string) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetSubscriberID(v)
	})
}

// UpdateSubscriberID sets the "subscriber_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateSubscriberID() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateSubscriberID()
	})
}

// SetProjectID sets the "project_id" field.
func (u *NotificationSubscriptionUpsertOne) SetProjectID(v uuid.UUID) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateProjectID() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateProjectID()
	})
}

// SetTriggerActivities sets the "trigger_activities" field.
func (u *NotificationSubscriptionUpsertOne) SetTriggerActivities(v string) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetTriggerActivities(v)
	})
}

// UpdateTriggerActivities sets the "trigger_activities" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateTriggerActivities() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateTriggerActivities()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *NotificationSubscriptionUpsertOne) SetCreatedBy(v string) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateCreatedBy() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *NotificationSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotificationSubscriptionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NotificationSubscriptionUpsertOne.ID is not supported by MySQL driver. Use NotificationSubscriptionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotificationSubscriptionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotificationSubscriptionCreateBulk is the builder for creating many NotificationSubscription entities in bulk.
type NotificationSubscriptionCreateBulk struct {
	config
	err      error
	builders []*NotificationSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the NotificationSubscription entities in the database.
func (_c *NotificationSubscriptionCreateBulk) Save(ctx context.Context) ([]*NotificationSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationSubscriptionCreateBulk) SaveX(ctx context.Context) []*NotificationSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationSubscriptionUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotificationSubscriptionUpsertBulk {
	_c.conflict = opts
	return &NotificationSubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationSubscriptionCreateBulk) OnConflictColumns(columns ...string) *NotificationSubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationSubscriptionUpsertBulk{
		create: _c,
	}
}

// NotificationSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of NotificationSubscription nodes.
type NotificationSubscriptionUpsertBulk struct {
	create *NotificationSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotificationSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationsubscription.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationSubscriptionUpsertBulk) UpdateNewValues() *NotificationSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(notificationsubscription.FieldID)
			}
			if _, exists := b.mutation.Created(); exists {
				s.SetIgnore(notificationsubscription.FieldCreated)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotificationSubscriptionUpsertBulk) Ignore() *NotificationSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationSubscriptionUpsertBulk) DoNothing() *NotificationSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *NotificationSubscriptionUpsertBulk) Update(set func(*NotificationSubscriptionUpsert)) *NotificationSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *NotificationSubscriptionUpsertBulk) SetScope(v string) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateScope() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateScope()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *NotificationSubscriptionUpsertBulk) SetAgentID(v uuid.UUID) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateAgentID() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateAgentID()
	})
}

// ClearAgentID clears the value of the "agent_id" field.
func (u *NotificationSubscriptionUpsertBulk) ClearAgentID() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.ClearAgentID()
	})
}

// SetSubscriberType sets the "subscriber_type" field.
func (u *NotificationSubscriptionUpsertBulk) SetSubscriberType(v string) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetSubscriberType(v)
	})
}

// UpdateSubscriberType sets the "subscriber_type" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateSubscriberType() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateSubscriberType()
	})
}

// SetSubscriberID sets the "subscriber_id" field.
func (u *NotificationSubscriptionUpsertBulk) SetSubscriberID(v string) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetSubscriberID(v)
	})
}

// UpdateSubscriberID sets the "subscriber_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateSubscriberID() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateSubscriberID()
	})
}

// SetProjectID sets the "project_id" field.
func (u *NotificationSubscriptionUpsertBulk) SetProjectID(v uuid.UUID) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateProjectID() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateProjectID()
	})
}

// SetTriggerActivities sets the "trigger_activities" field.
func (u *NotificationSubscriptionUpsertBulk) SetTriggerActivities(v string) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetTriggerActivities(v)
	})
}

// UpdateTriggerActivities sets the "trigger_activities" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateTriggerActivities() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateTriggerActivities()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *NotificationSubscriptionUpsertBulk) SetCreatedBy(v string) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateCreatedBy() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *NotificationSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotificationSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
