// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/scheduledevent"
	"github.com/google/uuid"
)

// ScheduledEventUpdate is the builder for updating ScheduledEvent entities.
type ScheduledEventUpdate struct {
	config
	hooks    []Hook
	mutation *ScheduledEventMutation
}

// Where appends a list predicates to the ScheduledEventUpdate builder.
func (_u *ScheduledEventUpdate) Where(ps ...predicate.ScheduledEvent) *ScheduledEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ScheduledEventUpdate) SetProjectID(v uuid.UUID) *ScheduledEventUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ScheduledEventUpdate) SetNillableProjectID(v *uuid.UUID) *ScheduledEventUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *ScheduledEventUpdate) SetEventType(v string) *ScheduledEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *ScheduledEventUpdate) SetNillableEventType(v *string) *ScheduledEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetFireAt sets the "fire_at" field.
func (_u *ScheduledEventUpdate) SetFireAt(v time.Time) *ScheduledEventUpdate {
	_u.mutation.SetFireAt(v)
	return _u
}

// SetNillableFireAt sets the "fire_at" field if the given value is not nil.
func (_u *ScheduledEventUpdate) SetNillableFireAt(v *time.Time) *ScheduledEventUpdate {
	if v != nil {
		_u.SetFireAt(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *ScheduledEventUpdate) SetPayload(v string) *ScheduledEventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *ScheduledEventUpdate) SetNillablePayload(v *string) *ScheduledEventUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScheduledEventUpdate) SetStatus(v string) *ScheduledEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScheduledEventUpdate) SetNillableStatus(v *string) *ScheduledEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ScheduledEventUpdate) SetCreatedBy(v string) *ScheduledEventUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ScheduledEventUpdate) SetNillableCreatedBy(v *string) *ScheduledEventUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ScheduledEventUpdate) ClearCreatedBy() *ScheduledEventUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetFiredAt sets the "fired_at" field.
func (_u *ScheduledEventUpdate) SetFiredAt(v time.Time) *ScheduledEventUpdate {
	_u.mutation.SetFiredAt(v)
	return _u
}

// SetNillableFiredAt sets the "fired_at" field if the given value is not nil.
func (_u *ScheduledEventUpdate) SetNillableFiredAt(v *time.Time) *ScheduledEventUpdate {
	if v != nil {
		_u.SetFiredAt(*v)
	}
	return _u
}

// ClearFiredAt clears the value of the "fired_at" field.
func (_u *ScheduledEventUpdate) ClearFiredAt() *ScheduledEventUpdate {
	_u.mutation.ClearFiredAt()
	return _u
}

// SetError sets the "error" field.
func (_u *ScheduledEventUpdate) SetError(v string) *ScheduledEventUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ScheduledEventUpdate) SetNillableError(v *string) *ScheduledEventUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *ScheduledEventUpdate) ClearError() *ScheduledEventUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetScheduleID sets the "schedule_id" field.
func (_u *ScheduledEventUpdate) SetScheduleID(v string) *ScheduledEventUpdate {
	_u.mutation.SetScheduleID(v)
	return _u
}

// SetNillableScheduleID sets the "schedule_id" field if the given value is not nil.
func (_u *ScheduledEventUpdate) SetNillableScheduleID(v *string) *ScheduledEventUpdate {
	if v != nil {
		_u.SetScheduleID(*v)
	}
	return _u
}

// ClearScheduleID clears the value of the "schedule_id" field.
func (_u *ScheduledEventUpdate) ClearScheduleID() *ScheduledEventUpdate {
	_u.mutation.ClearScheduleID()
	return _u
}

// Mutation returns the ScheduledEventMutation object of the builder.
func (_u *ScheduledEventUpdate) Mutation() *ScheduledEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScheduledEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduledEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScheduledEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduledEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduledEventUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := scheduledevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "ScheduledEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Payload(); ok {
		if err := scheduledevent.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "ScheduledEvent.payload": %w`, err)}
		}
	}
	return nil
}

func (_u *ScheduledEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scheduledevent.Table, scheduledevent.Columns, sqlgraph.NewFieldSpec(scheduledevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(scheduledevent.FieldProjectID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(scheduledevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FireAt(); ok {
		_spec.SetField(scheduledevent.FieldFireAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(scheduledevent.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(scheduledevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(scheduledevent.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(scheduledevent.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.FiredAt(); ok {
		_spec.SetField(scheduledevent.FieldFiredAt, field.TypeTime, value)
	}
	if _u.mutation.FiredAtCleared() {
		_spec.ClearField(scheduledevent.FieldFiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(scheduledevent.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(scheduledevent.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.ScheduleID(); ok {
		_spec.SetField(scheduledevent.FieldScheduleID, field.TypeString, value)
	}
	if _u.mutation.ScheduleIDCleared() {
		_spec.ClearField(scheduledevent.FieldScheduleID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scheduledevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScheduledEventUpdateOne is the builder for updating a single ScheduledEvent entity.
type ScheduledEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScheduledEventMutation
}

// SetProjectID sets the "project_id" field.
func (_u *ScheduledEventUpdateOne) SetProjectID(v uuid.UUID) *ScheduledEventUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ScheduledEventUpdateOne) SetNillableProjectID(v *uuid.UUID) *ScheduledEventUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *ScheduledEventUpdateOne) SetEventType(v string) *ScheduledEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *ScheduledEventUpdateOne) SetNillableEventType(v *string) *ScheduledEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetFireAt sets the "fire_at" field.
func (_u *ScheduledEventUpdateOne) SetFireAt(v time.Time) *ScheduledEventUpdateOne {
	_u.mutation.SetFireAt(v)
	return _u
}

// SetNillableFireAt sets the "fire_at" field if the given value is not nil.
func (_u *ScheduledEventUpdateOne) SetNillableFireAt(v *time.Time) *ScheduledEventUpdateOne {
	if v != nil {
		_u.SetFireAt(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *ScheduledEventUpdateOne) SetPayload(v string) *ScheduledEventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *ScheduledEventUpdateOne) SetNillablePayload(v *string) *ScheduledEventUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScheduledEventUpdateOne) SetStatus(v string) *ScheduledEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScheduledEventUpdateOne) SetNillableStatus(v *string) *ScheduledEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ScheduledEventUpdateOne) SetCreatedBy(v string) *ScheduledEventUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ScheduledEventUpdateOne) SetNillableCreatedBy(v *string) *ScheduledEventUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ScheduledEventUpdateOne) ClearCreatedBy() *ScheduledEventUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetFiredAt sets the "fired_at" field.
func (_u *ScheduledEventUpdateOne) SetFiredAt(v time.Time) *ScheduledEventUpdateOne {
	_u.mutation.SetFiredAt(v)
	return _u
}

// SetNillableFiredAt sets the "fired_at" field if the given value is not nil.
func (_u *ScheduledEventUpdateOne) SetNillableFiredAt(v *time.Time) *ScheduledEventUpdateOne {
	if v != nil {
		_u.SetFiredAt(*v)
	}
	return _u
}

// ClearFiredAt clears the value of the "fired_at" field.
func (_u *ScheduledEventUpdateOne) ClearFiredAt() *ScheduledEventUpdateOne {
	_u.mutation.ClearFiredAt()
	return _u
}

// SetError sets the "error" field.
func (_u *ScheduledEventUpdateOne) SetError(v string) *ScheduledEventUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ScheduledEventUpdateOne) SetNillableError(v *string) *ScheduledEventUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *ScheduledEventUpdateOne) ClearError() *ScheduledEventUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetScheduleID sets the "schedule_id" field.
func (_u *ScheduledEventUpdateOne) SetScheduleID(v string) *ScheduledEventUpdateOne {
	_u.mutation.SetScheduleID(v)
	return _u
}

// SetNillableScheduleID sets the "schedule_id" field if the given value is not nil.
func (_u *ScheduledEventUpdateOne) SetNillableScheduleID(v *string) *ScheduledEventUpdateOne {
	if v != nil {
		_u.SetScheduleID(*v)
	}
	return _u
}

// ClearScheduleID clears the value of the "schedule_id" field.
func (_u *ScheduledEventUpdateOne) ClearScheduleID() *ScheduledEventUpdateOne {
	_u.mutation.ClearScheduleID()
	return _u
}

// Mutation returns the ScheduledEventMutation object of the builder.
func (_u *ScheduledEventUpdateOne) Mutation() *ScheduledEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the ScheduledEventUpdate builder.
func (_u *ScheduledEventUpdateOne) Where(ps ...predicate.ScheduledEvent) *ScheduledEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScheduledEventUpdateOne) Select(field string, fields ...string) *ScheduledEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScheduledEvent entity.
func (_u *ScheduledEventUpdateOne) Save(ctx context.Context) (*ScheduledEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduledEventUpdateOne) SaveX(ctx context.Context) *ScheduledEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScheduledEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduledEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduledEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := scheduledevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "ScheduledEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Payload(); ok {
		if err := scheduledevent.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "ScheduledEvent.payload": %w`, err)}
		}
	}
	return nil
}

func (_u *ScheduledEventUpdateOne) sqlSave(ctx context.Context) (_node *ScheduledEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scheduledevent.Table, scheduledevent.Columns, sqlgraph.NewFieldSpec(scheduledevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScheduledEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scheduledevent.FieldID)
		for _, f := range fields {
			if !scheduledevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scheduledevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(scheduledevent.FieldProjectID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(scheduledevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FireAt(); ok {
		_spec.SetField(scheduledevent.FieldFireAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(scheduledevent.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(scheduledevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(scheduledevent.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(scheduledevent.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.FiredAt(); ok {
		_spec.SetField(scheduledevent.FieldFiredAt, field.TypeTime, value)
	}
	if _u.mutation.FiredAtCleared() {
		_spec.ClearField(scheduledevent.FieldFiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(scheduledevent.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(scheduledevent.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.ScheduleID(); ok {
		_spec.SetField(scheduledevent.FieldScheduleID, field.TypeString, value)
	}
	if _u.mutation.ScheduleIDCleared() {
		_spec.ClearField(scheduledevent.FieldScheduleID, field.TypeString)
	}
	_node = &ScheduledEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scheduledevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
