// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/secret"
	"github.com/google/uuid"
)

// SecretCreate is the builder for creating a Secret entity.
type SecretCreate struct {
	config
	mutation *SecretMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKey sets the "key" field.
func (_c *SecretCreate) SetKey(v string) *SecretCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetEncryptedValue sets the "encrypted_value" field.
func (_c *SecretCreate) SetEncryptedValue(v string) *SecretCreate {
	_c.mutation.SetEncryptedValue(v)
	return _c
}

// SetSecretRef sets the "secret_ref" field.
func (_c *SecretCreate) SetSecretRef(v string) *SecretCreate {
	_c.mutation.SetSecretRef(v)
	return _c
}

// SetNillableSecretRef sets the "secret_ref" field if the given value is not nil.
func (_c *SecretCreate) SetNillableSecretRef(v *string) *SecretCreate {
	if v != nil {
		_c.SetSecretRef(*v)
	}
	return _c
}

// SetSecretType sets the "secret_type" field.
func (_c *SecretCreate) SetSecretType(v secret.SecretType) *SecretCreate {
	_c.mutation.SetSecretType(v)
	return _c
}

// SetNillableSecretType sets the "secret_type" field if the given value is not nil.
func (_c *SecretCreate) SetNillableSecretType(v *secret.SecretType) *SecretCreate {
	if v != nil {
		_c.SetSecretType(*v)
	}
	return _c
}

// SetTarget sets the "target" field.
func (_c *SecretCreate) SetTarget(v string) *SecretCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_c *SecretCreate) SetNillableTarget(v *string) *SecretCreate {
	if v != nil {
		_c.SetTarget(*v)
	}
	return _c
}

// SetScope sets the "scope" field.
func (_c *SecretCreate) SetScope(v string) *SecretCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetScopeID sets the "scope_id" field.
func (_c *SecretCreate) SetScopeID(v string) *SecretCreate {
	_c.mutation.SetScopeID(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SecretCreate) SetDescription(v string) *SecretCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SecretCreate) SetNillableDescription(v *string) *SecretCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetInjectionMode sets the "injection_mode" field.
func (_c *SecretCreate) SetInjectionMode(v secret.InjectionMode) *SecretCreate {
	_c.mutation.SetInjectionMode(v)
	return _c
}

// SetNillableInjectionMode sets the "injection_mode" field if the given value is not nil.
func (_c *SecretCreate) SetNillableInjectionMode(v *secret.InjectionMode) *SecretCreate {
	if v != nil {
		_c.SetInjectionMode(*v)
	}
	return _c
}

// SetAllowProgeny sets the "allow_progeny" field.
func (_c *SecretCreate) SetAllowProgeny(v bool) *SecretCreate {
	_c.mutation.SetAllowProgeny(v)
	return _c
}

// SetNillableAllowProgeny sets the "allow_progeny" field if the given value is not nil.
func (_c *SecretCreate) SetNillableAllowProgeny(v *bool) *SecretCreate {
	if v != nil {
		_c.SetAllowProgeny(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *SecretCreate) SetVersion(v int) *SecretCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *SecretCreate) SetNillableVersion(v *int) *SecretCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SecretCreate) SetCreatedBy(v string) *SecretCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SecretCreate) SetNillableCreatedBy(v *string) *SecretCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SecretCreate) SetUpdatedBy(v string) *SecretCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *SecretCreate) SetNillableUpdatedBy(v *string) *SecretCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *SecretCreate) SetCreated(v time.Time) *SecretCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *SecretCreate) SetNillableCreated(v *time.Time) *SecretCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *SecretCreate) SetUpdated(v time.Time) *SecretCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *SecretCreate) SetNillableUpdated(v *time.Time) *SecretCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SecretCreate) SetID(v uuid.UUID) *SecretCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SecretCreate) SetNillableID(v *uuid.UUID) *SecretCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SecretMutation object of the builder.
func (_c *SecretCreate) Mutation() *SecretMutation {
	return _c.mutation
}

// Save creates the Secret in the database.
func (_c *SecretCreate) Save(ctx context.Context) (*Secret, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SecretCreate) SaveX(ctx context.Context) *Secret {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecretCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecretCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SecretCreate) defaults() {
	if _, ok := _c.mutation.SecretType(); !ok {
		v := secret.DefaultSecretType
		_c.mutation.SetSecretType(v)
	}
	if _, ok := _c.mutation.InjectionMode(); !ok {
		v := secret.DefaultInjectionMode
		_c.mutation.SetInjectionMode(v)
	}
	if _, ok := _c.mutation.AllowProgeny(); !ok {
		v := secret.DefaultAllowProgeny
		_c.mutation.SetAllowProgeny(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := secret.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := secret.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := secret.DefaultUpdated()
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := secret.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SecretCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Secret.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := secret.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Secret.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EncryptedValue(); !ok {
		return &ValidationError{Name: "encrypted_value", err: errors.New(`ent: missing required field "Secret.encrypted_value"`)}
	}
	if _, ok := _c.mutation.SecretType(); !ok {
		return &ValidationError{Name: "secret_type", err: errors.New(`ent: missing required field "Secret.secret_type"`)}
	}
	if v, ok := _c.mutation.SecretType(); ok {
		if err := secret.SecretTypeValidator(v); err != nil {
			return &ValidationError{Name: "secret_type", err: fmt.Errorf(`ent: validator failed for field "Secret.secret_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "Secret.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := secret.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Secret.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopeID(); !ok {
		return &ValidationError{Name: "scope_id", err: errors.New(`ent: missing required field "Secret.scope_id"`)}
	}
	if _, ok := _c.mutation.InjectionMode(); !ok {
		return &ValidationError{Name: "injection_mode", err: errors.New(`ent: missing required field "Secret.injection_mode"`)}
	}
	if v, ok := _c.mutation.InjectionMode(); ok {
		if err := secret.InjectionModeValidator(v); err != nil {
			return &ValidationError{Name: "injection_mode", err: fmt.Errorf(`ent: validator failed for field "Secret.injection_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AllowProgeny(); !ok {
		return &ValidationError{Name: "allow_progeny", err: errors.New(`ent: missing required field "Secret.allow_progeny"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Secret.version"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "Secret.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "Secret.updated"`)}
	}
	return nil
}

func (_c *SecretCreate) sqlSave(ctx context.Context) (*Secret, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SecretCreate) createSpec() (*Secret, *sqlgraph.CreateSpec) {
	var (
		_node = &Secret{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(secret.Table, sqlgraph.NewFieldSpec(secret.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(secret.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.EncryptedValue(); ok {
		_spec.SetField(secret.FieldEncryptedValue, field.TypeString, value)
		_node.EncryptedValue = value
	}
	if value, ok := _c.mutation.SecretRef(); ok {
		_spec.SetField(secret.FieldSecretRef, field.TypeString, value)
		_node.SecretRef = value
	}
	if value, ok := _c.mutation.SecretType(); ok {
		_spec.SetField(secret.FieldSecretType, field.TypeEnum, value)
		_node.SecretType = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(secret.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(secret.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.ScopeID(); ok {
		_spec.SetField(secret.FieldScopeID, field.TypeString, value)
		_node.ScopeID = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(secret.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.InjectionMode(); ok {
		_spec.SetField(secret.FieldInjectionMode, field.TypeEnum, value)
		_node.InjectionMode = value
	}
	if value, ok := _c.mutation.AllowProgeny(); ok {
		_spec.SetField(secret.FieldAllowProgeny, field.TypeBool, value)
		_node.AllowProgeny = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(secret.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(secret.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(secret.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(secret.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(secret.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Secret.Create().
//		SetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SecretUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *SecretCreate) OnConflict(opts ...sql.ConflictOption) *SecretUpsertOne {
	_c.conflict = opts
	return &SecretUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Secret.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SecretCreate) OnConflictColumns(columns ...string) *SecretUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SecretUpsertOne{
		create: _c,
	}
}

type (
	// SecretUpsertOne is the builder for "upsert"-ing
	//  one Secret node.
	SecretUpsertOne struct {
		create *SecretCreate
	}

	// SecretUpsert is the "OnConflict" setter.
	SecretUpsert struct {
		*sql.UpdateSet
	}
)

// SetKey sets the "key" field.
func (u *SecretUpsert) SetKey(v string) *SecretUpsert {
	u.Set(secret.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *SecretUpsert) UpdateKey() *SecretUpsert {
	u.SetExcluded(secret.FieldKey)
	return u
}

// SetEncryptedValue sets the "encrypted_value" field.
func (u *SecretUpsert) SetEncryptedValue(v string) *SecretUpsert {
	u.Set(secret.FieldEncryptedValue, v)
	return u
}

// UpdateEncryptedValue sets the "encrypted_value" field to the value that was provided on create.
func (u *SecretUpsert) UpdateEncryptedValue() *SecretUpsert {
	u.SetExcluded(secret.FieldEncryptedValue)
	return u
}

// SetSecretRef sets the "secret_ref" field.
func (u *SecretUpsert) SetSecretRef(v string) *SecretUpsert {
	u.Set(secret.FieldSecretRef, v)
	return u
}

// UpdateSecretRef sets the "secret_ref" field to the value that was provided on create.
func (u *SecretUpsert) UpdateSecretRef() *SecretUpsert {
	u.SetExcluded(secret.FieldSecretRef)
	return u
}

// ClearSecretRef clears the value of the "secret_ref" field.
func (u *SecretUpsert) ClearSecretRef() *SecretUpsert {
	u.SetNull(secret.FieldSecretRef)
	return u
}

// SetSecretType sets the "secret_type" field.
func (u *SecretUpsert) SetSecretType(v secret.SecretType) *SecretUpsert {
	u.Set(secret.FieldSecretType, v)
	return u
}

// UpdateSecretType sets the "secret_type" field to the value that was provided on create.
func (u *SecretUpsert) UpdateSecretType() *SecretUpsert {
	u.SetExcluded(secret.FieldSecretType)
	return u
}

// SetTarget sets the "target" field.
func (u *SecretUpsert) SetTarget(v string) *SecretUpsert {
	u.Set(secret.FieldTarget, v)
	return u
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *SecretUpsert) UpdateTarget() *SecretUpsert {
	u.SetExcluded(secret.FieldTarget)
	return u
}

// ClearTarget clears the value of the "target" field.
func (u *SecretUpsert) ClearTarget() *SecretUpsert {
	u.SetNull(secret.FieldTarget)
	return u
}

// SetScope sets the "scope" field.
func (u *SecretUpsert) SetScope(v string) *SecretUpsert {
	u.Set(secret.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SecretUpsert) UpdateScope() *SecretUpsert {
	u.SetExcluded(secret.FieldScope)
	return u
}

// SetScopeID sets the "scope_id" field.
func (u *SecretUpsert) SetScopeID(v string) *SecretUpsert {
	u.Set(secret.FieldScopeID, v)
	return u
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *SecretUpsert) UpdateScopeID() *SecretUpsert {
	u.SetExcluded(secret.FieldScopeID)
	return u
}

// SetDescription sets the "description" field.
func (u *SecretUpsert) SetDescription(v string) *SecretUpsert {
	u.Set(secret.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SecretUpsert) UpdateDescription() *SecretUpsert {
	u.SetExcluded(secret.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SecretUpsert) ClearDescription() *SecretUpsert {
	u.SetNull(secret.FieldDescription)
	return u
}

// SetInjectionMode sets the "injection_mode" field.
func (u *SecretUpsert) SetInjectionMode(v secret.InjectionMode) *SecretUpsert {
	u.Set(secret.FieldInjectionMode, v)
	return u
}

// UpdateInjectionMode sets the "injection_mode" field to the value that was provided on create.
func (u *SecretUpsert) UpdateInjectionMode() *SecretUpsert {
	u.SetExcluded(secret.FieldInjectionMode)
	return u
}

// SetAllowProgeny sets the "allow_progeny" field.
func (u *SecretUpsert) SetAllowProgeny(v bool) *SecretUpsert {
	u.Set(secret.FieldAllowProgeny, v)
	return u
}

// UpdateAllowProgeny sets the "allow_progeny" field to the value that was provided on create.
func (u *SecretUpsert) UpdateAllowProgeny() *SecretUpsert {
	u.SetExcluded(secret.FieldAllowProgeny)
	return u
}

// SetVersion sets the "version" field.
func (u *SecretUpsert) SetVersion(v int) *SecretUpsert {
	u.Set(secret.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SecretUpsert) UpdateVersion() *SecretUpsert {
	u.SetExcluded(secret.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *SecretUpsert) AddVersion(v int) *SecretUpsert {
	u.Add(secret.FieldVersion, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *SecretUpsert) SetCreatedBy(v string) *SecretUpsert {
	u.Set(secret.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SecretUpsert) UpdateCreatedBy() *SecretUpsert {
	u.SetExcluded(secret.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SecretUpsert) ClearCreatedBy() *SecretUpsert {
	u.SetNull(secret.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *SecretUpsert) SetUpdatedBy(v string) *SecretUpsert {
	u.Set(secret.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *SecretUpsert) UpdateUpdatedBy() *SecretUpsert {
	u.SetExcluded(secret.FieldUpdatedBy)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *SecretUpsert) ClearUpdatedBy() *SecretUpsert {
	u.SetNull(secret.FieldUpdatedBy)
	return u
}

// SetUpdated sets the "updated" field.
func (u *SecretUpsert) SetUpdated(v time.Time) *SecretUpsert {
	u.Set(secret.FieldUpdated, v)
	return u
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *SecretUpsert) UpdateUpdated() *SecretUpsert {
	u.SetExcluded(secret.FieldUpdated)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Secret.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(secret.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SecretUpsertOne) UpdateNewValues() *SecretUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(secret.FieldID)
		}
		if _, exists := u.create.mutation.Created(); exists {
			s.SetIgnore(secret.FieldCreated)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Secret.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SecretUpsertOne) Ignore() *SecretUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SecretUpsertOne) DoNothing() *SecretUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SecretCreate.OnConflict
// documentation for more info.
func (u *SecretUpsertOne) Update(set func(*SecretUpsert)) *SecretUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SecretUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *SecretUpsertOne) SetKey(v string) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateKey() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateKey()
	})
}

// SetEncryptedValue sets the "encrypted_value" field.
func (u *SecretUpsertOne) SetEncryptedValue(v string) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetEncryptedValue(v)
	})
}

// UpdateEncryptedValue sets the "encrypted_value" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateEncryptedValue() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateEncryptedValue()
	})
}

// SetSecretRef sets the "secret_ref" field.
func (u *SecretUpsertOne) SetSecretRef(v string) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetSecretRef(v)
	})
}

// UpdateSecretRef sets the "secret_ref" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateSecretRef() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateSecretRef()
	})
}

// ClearSecretRef clears the value of the "secret_ref" field.
func (u *SecretUpsertOne) ClearSecretRef() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.ClearSecretRef()
	})
}

// SetSecretType sets the "secret_type" field.
func (u *SecretUpsertOne) SetSecretType(v secret.SecretType) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetSecretType(v)
	})
}

// UpdateSecretType sets the "secret_type" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateSecretType() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateSecretType()
	})
}

// SetTarget sets the "target" field.
func (u *SecretUpsertOne) SetTarget(v string) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetTarget(v)
	})
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateTarget() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateTarget()
	})
}

// ClearTarget clears the value of the "target" field.
func (u *SecretUpsertOne) ClearTarget() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.ClearTarget()
	})
}

// SetScope sets the "scope" field.
func (u *SecretUpsertOne) SetScope(v string) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateScope() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateScope()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *SecretUpsertOne) SetScopeID(v string) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateScopeID() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateScopeID()
	})
}

// SetDescription sets the "description" field.
func (u *SecretUpsertOne) SetDescription(v string) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateDescription() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SecretUpsertOne) ClearDescription() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.ClearDescription()
	})
}

// SetInjectionMode sets the "injection_mode" field.
func (u *SecretUpsertOne) SetInjectionMode(v secret.InjectionMode) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetInjectionMode(v)
	})
}

// UpdateInjectionMode sets the "injection_mode" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateInjectionMode() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateInjectionMode()
	})
}

// SetAllowProgeny sets the "allow_progeny" field.
func (u *SecretUpsertOne) SetAllowProgeny(v bool) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetAllowProgeny(v)
	})
}

// UpdateAllowProgeny sets the "allow_progeny" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateAllowProgeny() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateAllowProgeny()
	})
}

// SetVersion sets the "version" field.
func (u *SecretUpsertOne) SetVersion(v int) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SecretUpsertOne) AddVersion(v int) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateVersion() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateVersion()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SecretUpsertOne) SetCreatedBy(v string) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateCreatedBy() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SecretUpsertOne) ClearCreatedBy() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *SecretUpsertOne) SetUpdatedBy(v string) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateUpdatedBy() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *SecretUpsertOne) ClearUpdatedBy() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdated sets the "updated" field.
func (u *SecretUpsertOne) SetUpdated(v time.Time) *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *SecretUpsertOne) UpdateUpdated() *SecretUpsertOne {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateUpdated()
	})
}

// Exec executes the query.
func (u *SecretUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SecretCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SecretUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SecretUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SecretUpsertOne.ID is not supported by MySQL driver. Use SecretUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SecretUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SecretCreateBulk is the builder for creating many Secret entities in bulk.
type SecretCreateBulk struct {
	config
	err      error
	builders []*SecretCreate
	conflict []sql.ConflictOption
}

// Save creates the Secret entities in the database.
func (_c *SecretCreateBulk) Save(ctx context.Context) ([]*Secret, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Secret, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SecretMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SecretCreateBulk) SaveX(ctx context.Context) []*Secret {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecretCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecretCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Secret.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SecretUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *SecretCreateBulk) OnConflict(opts ...sql.ConflictOption) *SecretUpsertBulk {
	_c.conflict = opts
	return &SecretUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Secret.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SecretCreateBulk) OnConflictColumns(columns ...string) *SecretUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SecretUpsertBulk{
		create: _c,
	}
}

// SecretUpsertBulk is the builder for "upsert"-ing
// a bulk of Secret nodes.
type SecretUpsertBulk struct {
	create *SecretCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Secret.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(secret.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SecretUpsertBulk) UpdateNewValues() *SecretUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(secret.FieldID)
			}
			if _, exists := b.mutation.Created(); exists {
				s.SetIgnore(secret.FieldCreated)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Secret.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SecretUpsertBulk) Ignore() *SecretUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SecretUpsertBulk) DoNothing() *SecretUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SecretCreateBulk.OnConflict
// documentation for more info.
func (u *SecretUpsertBulk) Update(set func(*SecretUpsert)) *SecretUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SecretUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *SecretUpsertBulk) SetKey(v string) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateKey() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateKey()
	})
}

// SetEncryptedValue sets the "encrypted_value" field.
func (u *SecretUpsertBulk) SetEncryptedValue(v string) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetEncryptedValue(v)
	})
}

// UpdateEncryptedValue sets the "encrypted_value" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateEncryptedValue() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateEncryptedValue()
	})
}

// SetSecretRef sets the "secret_ref" field.
func (u *SecretUpsertBulk) SetSecretRef(v string) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetSecretRef(v)
	})
}

// UpdateSecretRef sets the "secret_ref" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateSecretRef() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateSecretRef()
	})
}

// ClearSecretRef clears the value of the "secret_ref" field.
func (u *SecretUpsertBulk) ClearSecretRef() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.ClearSecretRef()
	})
}

// SetSecretType sets the "secret_type" field.
func (u *SecretUpsertBulk) SetSecretType(v secret.SecretType) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetSecretType(v)
	})
}

// UpdateSecretType sets the "secret_type" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateSecretType() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateSecretType()
	})
}

// SetTarget sets the "target" field.
func (u *SecretUpsertBulk) SetTarget(v string) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetTarget(v)
	})
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateTarget() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateTarget()
	})
}

// ClearTarget clears the value of the "target" field.
func (u *SecretUpsertBulk) ClearTarget() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.ClearTarget()
	})
}

// SetScope sets the "scope" field.
func (u *SecretUpsertBulk) SetScope(v string) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateScope() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateScope()
	})
}

// SetScopeID sets the "scope_id" field.
func (u *SecretUpsertBulk) SetScopeID(v string) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetScopeID(v)
	})
}

// UpdateScopeID sets the "scope_id" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateScopeID() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateScopeID()
	})
}

// SetDescription sets the "description" field.
func (u *SecretUpsertBulk) SetDescription(v string) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateDescription() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SecretUpsertBulk) ClearDescription() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.ClearDescription()
	})
}

// SetInjectionMode sets the "injection_mode" field.
func (u *SecretUpsertBulk) SetInjectionMode(v secret.InjectionMode) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetInjectionMode(v)
	})
}

// UpdateInjectionMode sets the "injection_mode" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateInjectionMode() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateInjectionMode()
	})
}

// SetAllowProgeny sets the "allow_progeny" field.
func (u *SecretUpsertBulk) SetAllowProgeny(v bool) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetAllowProgeny(v)
	})
}

// UpdateAllowProgeny sets the "allow_progeny" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateAllowProgeny() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateAllowProgeny()
	})
}

// SetVersion sets the "version" field.
func (u *SecretUpsertBulk) SetVersion(v int) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SecretUpsertBulk) AddVersion(v int) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateVersion() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateVersion()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SecretUpsertBulk) SetCreatedBy(v string) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateCreatedBy() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SecretUpsertBulk) ClearCreatedBy() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *SecretUpsertBulk) SetUpdatedBy(v string) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateUpdatedBy() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *SecretUpsertBulk) ClearUpdatedBy() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdated sets the "updated" field.
func (u *SecretUpsertBulk) SetUpdated(v time.Time) *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *SecretUpsertBulk) UpdateUpdated() *SecretUpsertBulk {
	return u.Update(func(s *SecretUpsert) {
		s.UpdateUpdated()
	})
}

// Exec executes the query.
func (u *SecretUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SecretCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SecretCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SecretUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
