// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/skillversion"
	"github.com/google/uuid"
)

// SkillVersion is the model entity for the SkillVersion schema.
type SkillVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SkillID holds the value of the "skill_id" field.
	SkillID string `json:"skill_id,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Status holds the value of the "status" field.
	Status skillversion.Status `json:"status,omitempty"`
	// ContentHash holds the value of the "content_hash" field.
	ContentHash string `json:"content_hash,omitempty"`
	// Files holds the value of the "files" field.
	Files string `json:"files,omitempty"`
	// PublisherID holds the value of the "publisher_id" field.
	PublisherID string `json:"publisher_id,omitempty"`
	// DeprecationMessage holds the value of the "deprecation_message" field.
	DeprecationMessage string `json:"deprecation_message,omitempty"`
	// ReplacementURI holds the value of the "replacement_uri" field.
	ReplacementURI string `json:"replacement_uri,omitempty"`
	// DownloadCount holds the value of the "download_count" field.
	DownloadCount int64 `json:"download_count,omitempty"`
	// Created holds the value of the "created" field.
	Created      time.Time `json:"created,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SkillVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case skillversion.FieldDownloadCount:
			values[i] = new(sql.NullInt64)
		case skillversion.FieldSkillID, skillversion.FieldVersion, skillversion.FieldStatus, skillversion.FieldContentHash, skillversion.FieldFiles, skillversion.FieldPublisherID, skillversion.FieldDeprecationMessage, skillversion.FieldReplacementURI:
			values[i] = new(sql.NullString)
		case skillversion.FieldCreated:
			values[i] = new(sql.NullTime)
		case skillversion.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SkillVersion fields.
func (_m *SkillVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case skillversion.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case skillversion.FieldSkillID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skill_id", values[i])
			} else if value.Valid {
				_m.SkillID = value.String
			}
		case skillversion.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case skillversion.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = skillversion.Status(value.String)
			}
		case skillversion.FieldContentHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_hash", values[i])
			} else if value.Valid {
				_m.ContentHash = value.String
			}
		case skillversion.FieldFiles:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field files", values[i])
			} else if value.Valid {
				_m.Files = value.String
			}
		case skillversion.FieldPublisherID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field publisher_id", values[i])
			} else if value.Valid {
				_m.PublisherID = value.String
			}
		case skillversion.FieldDeprecationMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deprecation_message", values[i])
			} else if value.Valid {
				_m.DeprecationMessage = value.String
			}
		case skillversion.FieldReplacementURI:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field replacement_uri", values[i])
			} else if value.Valid {
				_m.ReplacementURI = value.String
			}
		case skillversion.FieldDownloadCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field download_count", values[i])
			} else if value.Valid {
				_m.DownloadCount = value.Int64
			}
		case skillversion.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				_m.Created = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SkillVersion.
// This includes values selected through modifiers, order, etc.
func (_m *SkillVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SkillVersion.
// Note that you need to call SkillVersion.Unwrap() before calling this method if this SkillVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SkillVersion) Update() *SkillVersionUpdateOne {
	return NewSkillVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SkillVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SkillVersion) Unwrap() *SkillVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SkillVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SkillVersion) String() string {
	var builder strings.Builder
	builder.WriteString("SkillVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("skill_id=")
	builder.WriteString(_m.SkillID)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("content_hash=")
	builder.WriteString(_m.ContentHash)
	builder.WriteString(", ")
	builder.WriteString("files=")
	builder.WriteString(_m.Files)
	builder.WriteString(", ")
	builder.WriteString("publisher_id=")
	builder.WriteString(_m.PublisherID)
	builder.WriteString(", ")
	builder.WriteString("deprecation_message=")
	builder.WriteString(_m.DeprecationMessage)
	builder.WriteString(", ")
	builder.WriteString("replacement_uri=")
	builder.WriteString(_m.ReplacementURI)
	builder.WriteString(", ")
	builder.WriteString("download_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DownloadCount))
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(_m.Created.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SkillVersions is a parsable slice of SkillVersion.
type SkillVersions []*SkillVersion
