// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/subscriptiontemplate"
	"github.com/google/uuid"
)

// SubscriptionTemplateCreate is the builder for creating a SubscriptionTemplate entity.
type SubscriptionTemplateCreate struct {
	config
	mutation *SubscriptionTemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *SubscriptionTemplateCreate) SetName(v string) *SubscriptionTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *SubscriptionTemplateCreate) SetScope(v string) *SubscriptionTemplateCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *SubscriptionTemplateCreate) SetNillableScope(v *string) *SubscriptionTemplateCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetTriggerActivities sets the "trigger_activities" field.
func (_c *SubscriptionTemplateCreate) SetTriggerActivities(v string) *SubscriptionTemplateCreate {
	_c.mutation.SetTriggerActivities(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *SubscriptionTemplateCreate) SetProjectID(v uuid.UUID) *SubscriptionTemplateCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *SubscriptionTemplateCreate) SetNillableProjectID(v *uuid.UUID) *SubscriptionTemplateCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SubscriptionTemplateCreate) SetCreatedBy(v string) *SubscriptionTemplateCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SubscriptionTemplateCreate) SetID(v uuid.UUID) *SubscriptionTemplateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SubscriptionTemplateCreate) SetNillableID(v *uuid.UUID) *SubscriptionTemplateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SubscriptionTemplateMutation object of the builder.
func (_c *SubscriptionTemplateCreate) Mutation() *SubscriptionTemplateMutation {
	return _c.mutation
}

// Save creates the SubscriptionTemplate in the database.
func (_c *SubscriptionTemplateCreate) Save(ctx context.Context) (*SubscriptionTemplate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionTemplateCreate) SaveX(ctx context.Context) *SubscriptionTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionTemplateCreate) defaults() {
	if _, ok := _c.mutation.Scope(); !ok {
		v := subscriptiontemplate.DefaultScope
		_c.mutation.SetScope(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := subscriptiontemplate.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionTemplateCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SubscriptionTemplate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := subscriptiontemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubscriptionTemplate.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "SubscriptionTemplate.scope"`)}
	}
	if _, ok := _c.mutation.TriggerActivities(); !ok {
		return &ValidationError{Name: "trigger_activities", err: errors.New(`ent: missing required field "SubscriptionTemplate.trigger_activities"`)}
	}
	if v, ok := _c.mutation.TriggerActivities(); ok {
		if err := subscriptiontemplate.TriggerActivitiesValidator(v); err != nil {
			return &ValidationError{Name: "trigger_activities", err: fmt.Errorf(`ent: validator failed for field "SubscriptionTemplate.trigger_activities": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "SubscriptionTemplate.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := subscriptiontemplate.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "SubscriptionTemplate.created_by": %w`, err)}
		}
	}
	return nil
}

func (_c *SubscriptionTemplateCreate) sqlSave(ctx context.Context) (*SubscriptionTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionTemplateCreate) createSpec() (*SubscriptionTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptiontemplate.Table, sqlgraph.NewFieldSpec(subscriptiontemplate.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(subscriptiontemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(subscriptiontemplate.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.TriggerActivities(); ok {
		_spec.SetField(subscriptiontemplate.FieldTriggerActivities, field.TypeString, value)
		_node.TriggerActivities = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(subscriptiontemplate.FieldProjectID, field.TypeUUID, value)
		_node.ProjectID = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(subscriptiontemplate.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionTemplate.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionTemplateUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionTemplateCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionTemplateUpsertOne {
	_c.conflict = opts
	return &SubscriptionTemplateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionTemplateCreate) OnConflictColumns(columns ...string) *SubscriptionTemplateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionTemplateUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionTemplateUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionTemplate node.
	SubscriptionTemplateUpsertOne struct {
		create *SubscriptionTemplateCreate
	}

	// SubscriptionTemplateUpsert is the "OnConflict" setter.
	SubscriptionTemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *SubscriptionTemplateUpsert) SetName(v string) *SubscriptionTemplateUpsert {
	u.Set(subscriptiontemplate.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsert) UpdateName() *SubscriptionTemplateUpsert {
	u.SetExcluded(subscriptiontemplate.FieldName)
	return u
}

// SetScope sets the "scope" field.
func (u *SubscriptionTemplateUpsert) SetScope(v string) *SubscriptionTemplateUpsert {
	u.Set(subscriptiontemplate.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsert) UpdateScope() *SubscriptionTemplateUpsert {
	u.SetExcluded(subscriptiontemplate.FieldScope)
	return u
}

// SetTriggerActivities sets the "trigger_activities" field.
func (u *SubscriptionTemplateUpsert) SetTriggerActivities(v string) *SubscriptionTemplateUpsert {
	u.Set(subscriptiontemplate.FieldTriggerActivities, v)
	return u
}

// UpdateTriggerActivities sets the "trigger_activities" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsert) UpdateTriggerActivities() *SubscriptionTemplateUpsert {
	u.SetExcluded(subscriptiontemplate.FieldTriggerActivities)
	return u
}

// SetProjectID sets the "project_id" field.
func (u *SubscriptionTemplateUpsert) SetProjectID(v uuid.UUID) *SubscriptionTemplateUpsert {
	u.Set(subscriptiontemplate.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsert) UpdateProjectID() *SubscriptionTemplateUpsert {
	u.SetExcluded(subscriptiontemplate.FieldProjectID)
	return u
}

// ClearProjectID clears the value of the "project_id" field.
func (u *SubscriptionTemplateUpsert) ClearProjectID() *SubscriptionTemplateUpsert {
	u.SetNull(subscriptiontemplate.FieldProjectID)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *SubscriptionTemplateUpsert) SetCreatedBy(v string) *SubscriptionTemplateUpsert {
	u.Set(subscriptiontemplate.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsert) UpdateCreatedBy() *SubscriptionTemplateUpsert {
	u.SetExcluded(subscriptiontemplate.FieldCreatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SubscriptionTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(subscriptiontemplate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SubscriptionTemplateUpsertOne) UpdateNewValues() *SubscriptionTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(subscriptiontemplate.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionTemplate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionTemplateUpsertOne) Ignore() *SubscriptionTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionTemplateUpsertOne) DoNothing() *SubscriptionTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionTemplateCreate.OnConflict
// documentation for more info.
func (u *SubscriptionTemplateUpsertOne) Update(set func(*SubscriptionTemplateUpsert)) *SubscriptionTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SubscriptionTemplateUpsertOne) SetName(v string) *SubscriptionTemplateUpsertOne {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsertOne) UpdateName() *SubscriptionTemplateUpsertOne {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.UpdateName()
	})
}

// SetScope sets the "scope" field.
func (u *SubscriptionTemplateUpsertOne) SetScope(v string) *SubscriptionTemplateUpsertOne {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsertOne) UpdateScope() *SubscriptionTemplateUpsertOne {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.UpdateScope()
	})
}

// SetTriggerActivities sets the "trigger_activities" field.
func (u *SubscriptionTemplateUpsertOne) SetTriggerActivities(v string) *SubscriptionTemplateUpsertOne {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.SetTriggerActivities(v)
	})
}

// UpdateTriggerActivities sets the "trigger_activities" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsertOne) UpdateTriggerActivities() *SubscriptionTemplateUpsertOne {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.UpdateTriggerActivities()
	})
}

// SetProjectID sets the "project_id" field.
func (u *SubscriptionTemplateUpsertOne) SetProjectID(v uuid.UUID) *SubscriptionTemplateUpsertOne {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsertOne) UpdateProjectID() *SubscriptionTemplateUpsertOne {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.UpdateProjectID()
	})
}

// ClearProjectID clears the value of the "project_id" field.
func (u *SubscriptionTemplateUpsertOne) ClearProjectID() *SubscriptionTemplateUpsertOne {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.ClearProjectID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SubscriptionTemplateUpsertOne) SetCreatedBy(v string) *SubscriptionTemplateUpsertOne {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsertOne) UpdateCreatedBy() *SubscriptionTemplateUpsertOne {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *SubscriptionTemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionTemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionTemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionTemplateUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SubscriptionTemplateUpsertOne.ID is not supported by MySQL driver. Use SubscriptionTemplateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionTemplateUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionTemplateCreateBulk is the builder for creating many SubscriptionTemplate entities in bulk.
type SubscriptionTemplateCreateBulk struct {
	config
	err      error
	builders []*SubscriptionTemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionTemplate entities in the database.
func (_c *SubscriptionTemplateCreateBulk) Save(ctx context.Context) ([]*SubscriptionTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionTemplateCreateBulk) SaveX(ctx context.Context) []*SubscriptionTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionTemplate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionTemplateUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionTemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionTemplateUpsertBulk {
	_c.conflict = opts
	return &SubscriptionTemplateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionTemplateCreateBulk) OnConflictColumns(columns ...string) *SubscriptionTemplateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionTemplateUpsertBulk{
		create: _c,
	}
}

// SubscriptionTemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionTemplate nodes.
type SubscriptionTemplateUpsertBulk struct {
	create *SubscriptionTemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(subscriptiontemplate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SubscriptionTemplateUpsertBulk) UpdateNewValues() *SubscriptionTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(subscriptiontemplate.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionTemplate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionTemplateUpsertBulk) Ignore() *SubscriptionTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionTemplateUpsertBulk) DoNothing() *SubscriptionTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionTemplateCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionTemplateUpsertBulk) Update(set func(*SubscriptionTemplateUpsert)) *SubscriptionTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SubscriptionTemplateUpsertBulk) SetName(v string) *SubscriptionTemplateUpsertBulk {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsertBulk) UpdateName() *SubscriptionTemplateUpsertBulk {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.UpdateName()
	})
}

// SetScope sets the "scope" field.
func (u *SubscriptionTemplateUpsertBulk) SetScope(v string) *SubscriptionTemplateUpsertBulk {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsertBulk) UpdateScope() *SubscriptionTemplateUpsertBulk {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.UpdateScope()
	})
}

// SetTriggerActivities sets the "trigger_activities" field.
func (u *SubscriptionTemplateUpsertBulk) SetTriggerActivities(v string) *SubscriptionTemplateUpsertBulk {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.SetTriggerActivities(v)
	})
}

// UpdateTriggerActivities sets the "trigger_activities" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsertBulk) UpdateTriggerActivities() *SubscriptionTemplateUpsertBulk {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.UpdateTriggerActivities()
	})
}

// SetProjectID sets the "project_id" field.
func (u *SubscriptionTemplateUpsertBulk) SetProjectID(v uuid.UUID) *SubscriptionTemplateUpsertBulk {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsertBulk) UpdateProjectID() *SubscriptionTemplateUpsertBulk {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.UpdateProjectID()
	})
}

// ClearProjectID clears the value of the "project_id" field.
func (u *SubscriptionTemplateUpsertBulk) ClearProjectID() *SubscriptionTemplateUpsertBulk {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.ClearProjectID()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SubscriptionTemplateUpsertBulk) SetCreatedBy(v string) *SubscriptionTemplateUpsertBulk {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SubscriptionTemplateUpsertBulk) UpdateCreatedBy() *SubscriptionTemplateUpsertBulk {
	return u.Update(func(s *SubscriptionTemplateUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *SubscriptionTemplateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionTemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionTemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionTemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
